import { Client } from 'pg';

const connectionString = process.env.SUPABASE_DB_URL ?? process.env.DATABASE_URL;
if (!connectionString) throw new Error('SUPABASE_DB_URL (or DATABASE_URL) is required for RLS tests');

const DOMAIN_TABLES = [
  'profiles',
  'organizations',
  'memberships',
  'invoices',
  'refunds',
  'audit_events',
] as const;

// ----------------------------------------------------------------------------
// Role + JWT helpers. SET LOCAL ROLE only lasts for the current transaction,
// so we always BEGIN / ROLLBACK around the boundary. SET LOCAL config keys
// drive auth.uid()/auth.role() via the stub in apps/api/test/sql/000_auth_stub.sql.
// ----------------------------------------------------------------------------
async function asAuthenticated(
  client: Client,
  sub: string,
  fn: () => Promise<void>,
): Promise<void> {
  // NOTE: SET LOCAL does not support extended-query parameter binding, so we
  // interpolate the UUID literal. `sub` is generated by the fixture helper
  // (gen_random_uuid() under superuser), so injection is not a concern.
  await client.query('begin');
  try {
    await client.query(`set local role authenticated`);
    await client.query(`set local "request.jwt.claim.sub" = '${sub}'`);
    await client.query(`set local "request.jwt.claim.role" = 'authenticated'`);
    await fn();
    await client.query('rollback');
  } catch (e) {
    await client.query('rollback');
    throw e;
  }
}

async function asAnon(client: Client, fn: () => Promise<void>): Promise<void> {
  await client.query('begin');
  try {
    await client.query(`set local role anon`);
    await fn();
    await client.query('rollback');
  } catch (e) {
    await client.query('rollback');
    throw e;
  }
}

async function asSuperuserTx(client: Client, fn: () => Promise<void>): Promise<void> {
  await client.query('begin');
  try {
    await fn();
    await client.query('rollback');
  } catch (e) {
    await client.query('rollback');
    throw e;
  }
}

// ----------------------------------------------------------------------------
// Fixture helpers (run as superuser, outside any transaction so rows persist
// across the boundary tests).
// ----------------------------------------------------------------------------
async function createOrg(client: Client): Promise<string> {
  const { rows } = await client.query<{ id: string }>(
    `insert into public.organizations (name) values ('Test Org') returning id`,
  );
  return rows[0].id;
}

async function createUserWithMembership(
  client: Client,
  orgId: string,
  role: 'user' | 'manager' | 'organization_admin',
  status: 'active' | 'suspended' = 'active',
): Promise<string> {
  const { rows } = await client.query<{ id: string }>(
    `insert into auth.users default values returning id`,
  );
  const userId = rows[0].id;
  await client.query(
    `insert into public.profiles (user_id, display_name) values ($1::uuid, $2::text)`,
    [userId, `User ${userId.slice(0, 8)}`],
  );
  await client.query(
    `insert into public.memberships (organization_id, user_id, role, status) values ($1, $2, $3, $4)`,
    [orgId, userId, role, status],
  );
  return userId;
}

async function createInvoice(
  client: Client,
  orgId: string,
  ownerId: string,
  status: 'draft' | 'issued' | 'paid' | 'cancelled' = 'draft',
): Promise<string> {
  const { rows } = await client.query<{ id: string }>(
    `insert into public.invoices
       (organization_id, owner_id, customer_id, description, amount_minor, currency, status)
     values ($1, $2, 'cust-1', 'desc', 1000, 'USD', $3)
     returning id`,
    [orgId, ownerId, status],
  );
  return rows[0].id;
}

// ----------------------------------------------------------------------------
// Tests
// ----------------------------------------------------------------------------
describe('domain schema RLS flags', () => {
  let client: Client;
  beforeAll(async () => {
    client = new Client({ connectionString });
    await client.connect();
  });
  afterAll(async () => { await client.end(); });

  it('every domain table has ENABLE and FORCE ROW LEVEL SECURITY', async () => {
    const { rows } = await client.query<{ relname: string; relrowsecurity: boolean; relforcerowsecurity: boolean }>(
      `select relname, relrowsecurity, relforcerowsecurity
         from pg_class
        where relnamespace = 'public'::regnamespace
          and relkind = 'r'
          and relname in ('profiles','organizations','memberships','invoices','refunds','audit_events')
        order by relname`
    );
    expect(rows).toEqual(expect.arrayContaining([
      expect.objectContaining({ relname: 'audit_events', relrowsecurity: true, relforcerowsecurity: true }),
      expect.objectContaining({ relname: 'invoices',     relrowsecurity: true, relforcerowsecurity: true }),
      expect.objectContaining({ relname: 'memberships',  relrowsecurity: true, relforcerowsecurity: true }),
      expect.objectContaining({ relname: 'organizations',relrowsecurity: true, relforcerowsecurity: true }),
      expect.objectContaining({ relname: 'profiles',     relrowsecurity: true, relforcerowsecurity: true }),
      expect.objectContaining({ relname: 'refunds',      relrowsecurity: true, relforcerowsecurity: true }),
    ]));
  });
});

describe('anon boundary', () => {
  let client: Client;
  beforeAll(async () => {
    client = new Client({ connectionString });
    await client.connect();
  });
  afterAll(async () => { await client.end(); });

  it('health_check() returns true as anon', async () => {
    await asAnon(client, async () => {
      const { rows } = await client.query<{ health_check: boolean }>(
        `select public.health_check() as health_check`,
      );
      expect(rows[0].health_check).toBe(true);
    });
  });

  it.each(DOMAIN_TABLES)('select from public.%s as anon is denied', async (table) => {
    await expect(
      asAnon(client, async () => {
        await client.query(`select * from public.${table}`);
      }),
    ).rejects.toMatchObject({ code: '42501' });
  });
});

describe('authenticated column-write restrictions', () => {
  let client: Client;
  let orgId: string;
  let adminUserId: string;

  beforeAll(async () => {
    client = new Client({ connectionString });
    await client.connect();
    orgId = await createOrg(client);
    adminUserId = await createUserWithMembership(client, orgId, 'organization_admin');
  });
  afterAll(async () => { await client.end(); });

  it('insert into public.refunds as authenticated is denied', async () => {
    await expect(
      asAuthenticated(client, adminUserId, async () => {
        await client.query(
          `insert into public.refunds (invoice_id, organization_id, created_by, amount_minor, currency, reason, idempotency_key)
           values (gen_random_uuid(), gen_random_uuid(), gen_random_uuid(), 100, 'USD', 'r', 'k')`,
        );
      }),
    ).rejects.toMatchObject({ code: '42501' });
  });

  it('insert into public.audit_events as authenticated is denied', async () => {
    await expect(
      asAuthenticated(client, adminUserId, async () => {
        await client.query(
          `insert into public.audit_events (actor_id, organization_id, action, target_type, target_id, result, correlation_id)
           values (gen_random_uuid(), gen_random_uuid(), 'a', 't', '1', 'success', gen_random_uuid())`,
        );
      }),
    ).rejects.toMatchObject({ code: '42501' });
  });

  it('update public.invoices.organization_id as authenticated is denied (column grant covers status only)', async () => {
    const invoiceId = await createInvoice(client, orgId, adminUserId);
    await expect(
      asAuthenticated(client, adminUserId, async () => {
        await client.query(
          `update public.invoices set organization_id = gen_random_uuid() where id = $1`,
          [invoiceId],
        );
      }),
    ).rejects.toMatchObject({ code: '42501' });
  });

  it('update public.invoices.customer_id as authenticated is denied (no UPDATE grant on customer_id)', async () => {
    const invoiceId = await createInvoice(client, orgId, adminUserId);
    await expect(
      asAuthenticated(client, adminUserId, async () => {
        await client.query(
          `update public.invoices set customer_id = 'new-cust' where id = $1`,
          [invoiceId],
        );
      }),
    ).rejects.toMatchObject({ code: '42501' });
  });
});

describe('CHECK constraints on public.invoices', () => {
  let client: Client;
  let orgId: string;
  let ownerId: string;

  beforeAll(async () => {
    client = new Client({ connectionString });
    await client.connect();
    orgId = await createOrg(client);
    ownerId = await createUserWithMembership(client, orgId, 'organization_admin');
  });
  afterAll(async () => { await client.end(); });

  async function expectCheckViolation(makeColumn: string, value: unknown): Promise<void> {
    // Seed one valid invoice per check (the UPDATE is what violates the CHECK).
    const invoiceId = await createInvoice(client, orgId, ownerId);
    await expect(
      client.query(
        `update public.invoices set ${makeColumn} = $1 where id = $2`,
        [value as never, invoiceId],
      ),
    ).rejects.toMatchObject({ code: '23514' });
  }

  it('amount_minor = 0 violates range check', async () => {
    await expectCheckViolation('amount_minor', 0);
  });

  it('amount_minor = 9007199254740992 violates upper bound (bigint max is 9007199254740991)', async () => {
    await expectCheckViolation('amount_minor', '9007199254740992');
  });

  it('amount_minor = -1 violates lower bound', async () => {
    await expectCheckViolation('amount_minor', -1);
  });

  it("currency = 'usd' violates ^[A-Z]{3}$ check", async () => {
    await expectCheckViolation('currency', 'usd');
  });

  it("currency = 'US' violates length-3 check", async () => {
    await expectCheckViolation('currency', 'US');
  });

  it("currency = 'USDD' is rejected (22001 string_data_right_truncation from char(3) cast — fires before the CHECK)", async () => {
    const invoiceId = await createInvoice(client, orgId, ownerId);
    await expect(
      client.query(
        `update public.invoices set currency = $1 where id = $2`,
        ['USDD', invoiceId],
      ),
    ).rejects.toMatchObject({ code: '22001' });
  });

  it('customer_id = empty string violates char_length >= 1 check', async () => {
    await expectCheckViolation('customer_id', '');
  });

  it('customer_id of 129 chars violates char_length <= 128 check', async () => {
    await expectCheckViolation('customer_id', 'x'.repeat(129));
  });

  it('description = empty string violates char_length >= 1 check', async () => {
    await expectCheckViolation('description', '');
  });
});

describe('invoice state machine trigger', () => {
  let client: Client;
  let orgId: string;
  let ownerId: string;

  beforeAll(async () => {
    client = new Client({ connectionString });
    await client.connect();
    orgId = await createOrg(client);
    ownerId = await createUserWithMembership(client, orgId, 'organization_admin');
  });
  afterAll(async () => { await client.end(); });

  async function expectTransition(
    from: 'draft' | 'issued' | 'paid' | 'cancelled',
    to: 'draft' | 'issued' | 'paid' | 'cancelled',
    shouldSucceed: boolean,
  ): Promise<void> {
    const invoiceId = await createInvoice(client, orgId, ownerId, from);
    if (shouldSucceed) {
      await asSuperuserTx(client, async () => {
        await client.query(
          `update public.invoices set status = $1 where id = $2`,
          [to, invoiceId],
        );
      });
    } else {
      await expect(
        asSuperuserTx(client, async () => {
          await client.query(
            `update public.invoices set status = $1 where id = $2`,
            [to, invoiceId],
          );
        }),
      ).rejects.toMatchObject({ message: expect.stringMatching(/invalid_state/) });
    }
  }

  it('draft -> issued succeeds', () => { return expectTransition('draft', 'issued', true); });
  it('draft -> cancelled succeeds', () => { return expectTransition('draft', 'cancelled', true); });
  it('issued -> paid succeeds', () => { return expectTransition('issued', 'paid', true); });
  it('issued -> cancelled succeeds', () => { return expectTransition('issued', 'cancelled', true); });
  it('paid -> paid succeeds (no-op)', () => { return expectTransition('paid', 'paid', true); });
  it('paid -> cancelled raises invalid_state (P0001)', () => { return expectTransition('paid', 'cancelled', false); });
  it('paid -> issued raises invalid_state (P0001)', () => { return expectTransition('paid', 'issued', false); });
  it('issued -> draft raises invalid_state (P0001)', () => { return expectTransition('issued', 'draft', false); });
});

describe('last-admin trigger', () => {
  let client: Client;

  beforeAll(async () => {
    client = new Client({ connectionString });
    await client.connect();
  });
  afterAll(async () => { await client.end(); });

  it('demoting the sole active admin raises last_admin (P0001)', async () => {
    const orgId = await createOrg(client);
    const adminId = await createUserWithMembership(client, orgId, 'organization_admin');
    await createUserWithMembership(client, orgId, 'user');
    await expect(
      asSuperuserTx(client, async () => {
        await client.query(
          `update public.memberships set role = 'manager' where organization_id = $1 and user_id = $2`,
          [orgId, adminId],
        );
      }),
    ).rejects.toMatchObject({ message: expect.stringMatching(/last_admin/) });
  });

  it('suspending the sole active admin raises last_admin (P0001)', async () => {
    const orgId = await createOrg(client);
    const adminId = await createUserWithMembership(client, orgId, 'organization_admin');
    await createUserWithMembership(client, orgId, 'user');
    await expect(
      asSuperuserTx(client, async () => {
        await client.query(
          `update public.memberships set status = 'suspended' where organization_id = $1 and user_id = $2`,
          [orgId, adminId],
        );
      }),
    ).rejects.toMatchObject({ message: expect.stringMatching(/last_admin/) });
  });

  it('demoting one of two active admins succeeds; demoting the other then raises last_admin', async () => {
    const orgId = await createOrg(client);
    const adminAId = await createUserWithMembership(client, orgId, 'organization_admin');
    await createUserWithMembership(client, orgId, 'organization_admin');
    // Demote adminA — second admin still active, succeeds.
    await asSuperuserTx(client, async () => {
      await client.query(
        `update public.memberships set role = 'manager' where organization_id = $1 and user_id = $2`,
        [orgId, adminAId],
      );
    });
    // Now only one admin remains; suspending them must fail.
    await expect(
      asSuperuserTx(client, async () => {
        await client.query(
          `update public.memberships set status = 'suspended' where organization_id = $1 and role = 'organization_admin' and status = 'active'`,
          [orgId],
        );
      }),
    ).rejects.toMatchObject({ message: expect.stringMatching(/last_admin/) });
  });
});