import { execSync } from 'node:child_process';
import { Client } from 'pg';
import { SEED_IDENTITIES, SEED_IDS } from './helpers/seed-identities';
import { signIn, visibleInvoiceIds, decodeAccessToken } from './helpers/auth';
import { closePool } from './helpers/db';

const connectionString = process.env.SUPABASE_DB_URL ?? process.env.DATABASE_URL;
if (!connectionString) throw new Error('SUPABASE_DB_URL (or DATABASE_URL) is required for RLS tests');

const DOMAIN_TABLES = [
  'profiles',
  'organizations',
  'memberships',
  'invoices',
  'refunds',
  'audit_events',
] as const;

// ----------------------------------------------------------------------------
// Role + JWT helpers. SET LOCAL ROLE only lasts for the current transaction,
// so we always BEGIN / ROLLBACK around the boundary. SET LOCAL config keys
// drive auth.uid()/auth.role() via the stub in apps/api/test/sql/000_auth_stub.sql.
// ----------------------------------------------------------------------------
async function asAuthenticated(
  client: Client,
  sub: string,
  fn: () => Promise<void>,
): Promise<void> {
  // NOTE: SET LOCAL does not support extended-query parameter binding, so we
  // interpolate the UUID literal. `sub` is generated by the fixture helper
  // (gen_random_uuid() under superuser), so injection is not a concern.
  await client.query('begin');
  try {
    await client.query(`set local role authenticated`);
    await client.query(`set local "request.jwt.claim.sub" = '${sub}'`);
    await client.query(`set local "request.jwt.claim.role" = 'authenticated'`);
    await fn();
    await client.query('rollback');
  } catch (e) {
    await client.query('rollback');
    throw e;
  }
}

async function asAnon(client: Client, fn: () => Promise<void>): Promise<void> {
  await client.query('begin');
  try {
    await client.query(`set local role anon`);
    await fn();
    await client.query('rollback');
  } catch (e) {
    await client.query('rollback');
    throw e;
  }
}

async function asSuperuserTx(client: Client, fn: () => Promise<void>): Promise<void> {
  await client.query('begin');
  try {
    await fn();
    await client.query('rollback');
  } catch (e) {
    await client.query('rollback');
    throw e;
  }
}

// ----------------------------------------------------------------------------
// Fixture helpers (run as superuser, outside any transaction so rows persist
// across the boundary tests).
// ----------------------------------------------------------------------------
async function createOrg(client: Client): Promise<string> {
  const { rows } = await client.query<{ id: string }>(
    `insert into public.organizations (name) values ('Test Org') returning id`,
  );
  return rows[0].id;
}

async function createUserWithMembership(
  client: Client,
  orgId: string,
  role: 'user' | 'manager' | 'organization_admin',
  status: 'active' | 'suspended' = 'active',
): Promise<string> {
  const { rows } = await client.query<{ id: string }>(
    `insert into auth.users (id, email, encrypted_password) values (gen_random_uuid()::uuid, gen_random_uuid()::text||'@test.com', '$2a$10$x') returning id`,
  );
  const userId = rows[0].id;
  await client.query(
    `insert into public.profiles (user_id, display_name) values ($1::uuid, $2::text)`,
    [userId, `User ${userId.slice(0, 8)}`],
  );
  await client.query(
    `insert into public.memberships (organization_id, user_id, role, status) values ($1, $2, $3, $4)`,
    [orgId, userId, role, status],
  );
  return userId;
}

async function createInvoice(
  client: Client,
  orgId: string,
  ownerId: string,
  status: 'draft' | 'issued' | 'paid' | 'cancelled' = 'draft',
): Promise<string> {
  const { rows } = await client.query<{ id: string }>(
    `insert into public.invoices
       (organization_id, owner_id, customer_id, description, amount_minor, currency, status)
     values ($1, $2, 'cust-1', 'desc', 1000, 'USD', $3)
     returning id`,
    [orgId, ownerId, status],
  );
  return rows[0].id;
}

// ----------------------------------------------------------------------------
// Tests
// ----------------------------------------------------------------------------
describe('domain schema RLS flags', () => {
  let client: Client;
  beforeAll(async () => {
    client = new Client({ connectionString });
    await client.connect();
  });
  afterAll(async () => { await client.end(); });

  it('every domain table has ENABLE and FORCE ROW LEVEL SECURITY', async () => {
    const { rows } = await client.query<{ relname: string; relrowsecurity: boolean; relforcerowsecurity: boolean }>(
      `select relname, relrowsecurity, relforcerowsecurity
         from pg_class
        where relnamespace = 'public'::regnamespace
          and relkind = 'r'
          and relname in ('profiles','organizations','memberships','invoices','refunds','audit_events')
        order by relname`
    );
    expect(rows).toEqual(expect.arrayContaining([
      expect.objectContaining({ relname: 'audit_events', relrowsecurity: true, relforcerowsecurity: true }),
      expect.objectContaining({ relname: 'invoices',     relrowsecurity: true, relforcerowsecurity: true }),
      expect.objectContaining({ relname: 'memberships',  relrowsecurity: true, relforcerowsecurity: true }),
      expect.objectContaining({ relname: 'organizations',relrowsecurity: true, relforcerowsecurity: true }),
      expect.objectContaining({ relname: 'profiles',     relrowsecurity: true, relforcerowsecurity: true }),
      expect.objectContaining({ relname: 'refunds',      relrowsecurity: true, relforcerowsecurity: true }),
    ]));
  });
});

describe('anon boundary', () => {
  let client: Client;
  beforeAll(async () => {
    client = new Client({ connectionString });
    await client.connect();
  });
  afterAll(async () => { await client.end(); });

  it('health_check() returns true as anon', async () => {
    await asAnon(client, async () => {
      const { rows } = await client.query<{ health_check: boolean }>(
        `select public.health_check() as health_check`,
      );
      expect(rows[0].health_check).toBe(true);
    });
  });

  it.each(DOMAIN_TABLES)('select from public.%s as anon is denied', async (table) => {
    await expect(
      asAnon(client, async () => {
        await client.query(`select * from public.${table}`);
      }),
    ).rejects.toMatchObject({ code: '42501' });
  });
});

describe('authenticated column-write restrictions', () => {
  let client: Client;
  let orgId: string;
  let adminUserId: string;

  beforeAll(async () => {
    client = new Client({ connectionString });
    await client.connect();
    orgId = await createOrg(client);
    adminUserId = await createUserWithMembership(client, orgId, 'organization_admin');
  });
  afterAll(async () => { await client.end(); });

  it('insert into public.refunds as authenticated is denied', async () => {
    await expect(
      asAuthenticated(client, adminUserId, async () => {
        await client.query(
          `insert into public.refunds (invoice_id, organization_id, created_by, amount_minor, currency, reason, idempotency_key)
           values (gen_random_uuid(), gen_random_uuid(), gen_random_uuid(), 100, 'USD', 'r', 'k')`,
        );
      }),
    ).rejects.toMatchObject({ code: '42501' });
  });

  it('insert into public.audit_events as authenticated is denied', async () => {
    await expect(
      asAuthenticated(client, adminUserId, async () => {
        await client.query(
          `insert into public.audit_events (actor_id, organization_id, action, target_type, target_id, result, correlation_id)
           values (gen_random_uuid(), gen_random_uuid(), 'a', 't', '1', 'success', gen_random_uuid())`,
        );
      }),
    ).rejects.toMatchObject({ code: '42501' });
  });

  it('update public.invoices.organization_id as authenticated is denied (column grant covers status only)', async () => {
    const invoiceId = await createInvoice(client, orgId, adminUserId);
    await expect(
      asAuthenticated(client, adminUserId, async () => {
        await client.query(
          `update public.invoices set organization_id = gen_random_uuid() where id = $1`,
          [invoiceId],
        );
      }),
    ).rejects.toMatchObject({ code: '42501' });
  });

  it('update public.invoices.customer_id as authenticated is denied (no UPDATE grant on customer_id)', async () => {
    const invoiceId = await createInvoice(client, orgId, adminUserId);
    await expect(
      asAuthenticated(client, adminUserId, async () => {
        await client.query(
          `update public.invoices set customer_id = 'new-cust' where id = $1`,
          [invoiceId],
        );
      }),
    ).rejects.toMatchObject({ code: '42501' });
  });
});

describe('CHECK constraints on public.invoices', () => {
  let client: Client;
  let orgId: string;
  let ownerId: string;

  beforeAll(async () => {
    client = new Client({ connectionString });
    await client.connect();
    orgId = await createOrg(client);
    ownerId = await createUserWithMembership(client, orgId, 'organization_admin');
  });
  afterAll(async () => { await client.end(); });

  async function expectCheckViolation(makeColumn: string, value: unknown): Promise<void> {
    // Seed one valid invoice per check (the UPDATE is what violates the CHECK).
    const invoiceId = await createInvoice(client, orgId, ownerId);
    await expect(
      client.query(
        `update public.invoices set ${makeColumn} = $1 where id = $2`,
        [value as never, invoiceId],
      ),
    ).rejects.toMatchObject({ code: '23514' });
  }

  it('amount_minor = 0 violates range check', async () => {
    await expectCheckViolation('amount_minor', 0);
  });

  it('amount_minor = 9007199254740992 violates upper bound (bigint max is 9007199254740991)', async () => {
    await expectCheckViolation('amount_minor', '9007199254740992');
  });

  it('amount_minor = -1 violates lower bound', async () => {
    await expectCheckViolation('amount_minor', -1);
  });

  it("currency = 'usd' violates ^[A-Z]{3}$ check", async () => {
    await expectCheckViolation('currency', 'usd');
  });

  it("currency = 'US' violates length-3 check", async () => {
    await expectCheckViolation('currency', 'US');
  });

  it("currency = 'USDD' is rejected (22001 string_data_right_truncation from char(3) cast — fires before the CHECK)", async () => {
    const invoiceId = await createInvoice(client, orgId, ownerId);
    await expect(
      client.query(
        `update public.invoices set currency = $1 where id = $2`,
        ['USDD', invoiceId],
      ),
    ).rejects.toMatchObject({ code: '22001' });
  });

  it('customer_id = empty string violates char_length >= 1 check', async () => {
    await expectCheckViolation('customer_id', '');
  });

  it('customer_id of 129 chars violates char_length <= 128 check', async () => {
    await expectCheckViolation('customer_id', 'x'.repeat(129));
  });

  it('description = empty string violates char_length >= 1 check', async () => {
    await expectCheckViolation('description', '');
  });
});

describe('invoice state machine trigger', () => {
  let client: Client;
  let orgId: string;
  let ownerId: string;

  beforeAll(async () => {
    client = new Client({ connectionString });
    await client.connect();
    orgId = await createOrg(client);
    ownerId = await createUserWithMembership(client, orgId, 'organization_admin');
  });
  afterAll(async () => { await client.end(); });

  async function expectTransition(
    from: 'draft' | 'issued' | 'paid' | 'cancelled',
    to: 'draft' | 'issued' | 'paid' | 'cancelled',
    shouldSucceed: boolean,
  ): Promise<void> {
    const invoiceId = await createInvoice(client, orgId, ownerId, from);
    if (shouldSucceed) {
      await asSuperuserTx(client, async () => {
        await client.query(
          `update public.invoices set status = $1 where id = $2`,
          [to, invoiceId],
        );
      });
    } else {
      await expect(
        asSuperuserTx(client, async () => {
          await client.query(
            `update public.invoices set status = $1 where id = $2`,
            [to, invoiceId],
          );
        }),
      ).rejects.toMatchObject({ message: expect.stringMatching(/invalid_state/) });
    }
  }

  it('draft -> issued succeeds', () => { return expectTransition('draft', 'issued', true); });
  it('draft -> cancelled succeeds', () => { return expectTransition('draft', 'cancelled', true); });
  it('issued -> paid succeeds', () => { return expectTransition('issued', 'paid', true); });
  it('issued -> cancelled succeeds', () => { return expectTransition('issued', 'cancelled', true); });
  it('paid -> paid succeeds (no-op)', () => { return expectTransition('paid', 'paid', true); });
  it('paid -> cancelled raises invalid_state (P0001)', () => { return expectTransition('paid', 'cancelled', false); });
  it('paid -> issued raises invalid_state (P0001)', () => { return expectTransition('paid', 'issued', false); });
  it('issued -> draft raises invalid_state (P0001)', () => { return expectTransition('issued', 'draft', false); });
});

describe('last-admin trigger', () => {
  let client: Client;

  beforeAll(async () => {
    client = new Client({ connectionString });
    await client.connect();
  });
  afterAll(async () => { await client.end(); });

  it('demoting the sole active admin raises last_admin (P0001)', async () => {
    const orgId = await createOrg(client);
    const adminId = await createUserWithMembership(client, orgId, 'organization_admin');
    await createUserWithMembership(client, orgId, 'user');
    await expect(
      asSuperuserTx(client, async () => {
        await client.query(
          `update public.memberships set role = 'manager' where organization_id = $1 and user_id = $2`,
          [orgId, adminId],
        );
      }),
    ).rejects.toMatchObject({ message: expect.stringMatching(/last_admin/) });
  });

  it('suspending the sole active admin raises last_admin (P0001)', async () => {
    const orgId = await createOrg(client);
    const adminId = await createUserWithMembership(client, orgId, 'organization_admin');
    await createUserWithMembership(client, orgId, 'user');
    await expect(
      asSuperuserTx(client, async () => {
        await client.query(
          `update public.memberships set status = 'suspended' where organization_id = $1 and user_id = $2`,
          [orgId, adminId],
        );
      }),
    ).rejects.toMatchObject({ message: expect.stringMatching(/last_admin/) });
  });

  it('demoting one of two active admins succeeds; demoting the other then raises last_admin', async () => {
    const orgId = await createOrg(client);
    const adminAId = await createUserWithMembership(client, orgId, 'organization_admin');
    await createUserWithMembership(client, orgId, 'organization_admin');
    // Demote adminA — second admin still active, succeeds.
    await asSuperuserTx(client, async () => {
      await client.query(
        `update public.memberships set role = 'manager' where organization_id = $1 and user_id = $2`,
        [orgId, adminAId],
      );
    });
    // Now only one admin remains; suspending them must fail.
    await expect(
      asSuperuserTx(client, async () => {
        await client.query(
          `update public.memberships set status = 'suspended' where organization_id = $1 and role = 'organization_admin' and status = 'active'`,
          [orgId],
        );
      }),
    ).rejects.toMatchObject({ message: expect.stringMatching(/last_admin/) });
  });
});

// ----------------------------------------------------------------------------
// Task 3 — visibility against the deterministic seed (apps/api/test/sql/003_seed.sql).
// These tests require db:seed to have been run. They use caller-scoped RLS
// queries against public.invoices; the shared SELECT policy is `invoices_select_visible`
// which branches on active_membership_role(organization_id).
// ----------------------------------------------------------------------------

describe('seed visibility (Task 3)', () => {
  function runReset(): void {
    // Idempotent: db:seed applies auth stub + schema + seed. Safe to re-run.
    execSync('npm run db:seed -w @continuous-security-demo/api', {
      stdio: 'pipe',
      env: process.env,
    });
  }

  it('alphaUserA signs in and sees only own invoice', async () => {
    const token = await signIn(SEED_IDENTITIES.alphaUserA);
    expect(token.split('.')).toHaveLength(3); // JWT header.payload.signature
    expect(await visibleInvoiceIds(token)).toEqual([SEED_IDS.alphaUserAInvoiceDraft]);
  });

  it('alphaUserB sees own invoice only (issued)', async () => {
    const token = await signIn(SEED_IDENTITIES.alphaUserB);
    expect(await visibleInvoiceIds(token)).toEqual([SEED_IDS.alphaUserBInvoiceIssued]);
  });

  it('alphaManager sees all Alpha invoices', async () => {
    const token = await signIn(SEED_IDENTITIES.alphaManager);
    expect(await visibleInvoiceIds(token).then((arr) => arr.sort())).toEqual(
      [SEED_IDS.alphaUserAInvoiceDraft, SEED_IDS.alphaUserBInvoiceIssued].sort(),
    );
  });

  it('alphaAdmin sees all Alpha invoices', async () => {
    const token = await signIn(SEED_IDENTITIES.alphaAdmin);
    expect(await visibleInvoiceIds(token).then((arr) => arr.sort())).toEqual(
      [SEED_IDS.alphaUserAInvoiceDraft, SEED_IDS.alphaUserBInvoiceIssued].sort(),
    );
  });

  it('alphaSuspended sees no invoices', async () => {
    const token = await signIn(SEED_IDENTITIES.alphaSuspended);
    expect(await visibleInvoiceIds(token)).toEqual([]);
  });

  it('betaAdmin sees only Beta invoice', async () => {
    const token = await signIn(SEED_IDENTITIES.betaAdmin);
    expect(await visibleInvoiceIds(token)).toEqual([SEED_IDS.betaAdminInvoice]);
  });

  it('seed is deterministic across resets', async () => {
    const first = await visibleInvoiceIds(await signIn(SEED_IDENTITIES.alphaManager));
    runReset();
    const second = await visibleInvoiceIds(await signIn(SEED_IDENTITIES.alphaManager));
    expect(second.sort()).toEqual(first.sort());
  }, 120000);

  afterAll(async () => {
    await closePool();
  });
});

// ----------------------------------------------------------------------------
// Task 6 — organizations + memberships + last-admin enforcement.
// Exercises the existing RLS policies (memberships_select_self,
// memberships_select_tenant, memberships_update_admin) and the
// enforce_last_admin() trigger under real Postgres role + JWT claims.
// ----------------------------------------------------------------------------

describe('Task 6: organization membership reads', () => {
  let client: Client;
  beforeAll(async () => {
    client = new Client({ connectionString });
    await client.connect();
  });
  afterAll(async () => { await client.end(); });

  it('active admin sees own organization row in public.organizations', async () => {
    const token = await signIn(SEED_IDENTITIES.alphaAdmin);
    const claims = await decodeAccessToken(token);
    await asAuthenticated(client, claims.sub, async () => {
      const { rows } = await client.query<{ id: string; name: string }>(
        `select id, name from public.organizations where id = $1`,
        [SEED_IDS.alphaOrg],
      );
      expect(rows).toEqual([{ id: SEED_IDS.alphaOrg, name: 'Alpha' }]);
    });
  });

  it('active admin of Alpha sees only Alpha memberships in own tenant', async () => {
    const token = await signIn(SEED_IDENTITIES.alphaAdmin);
    const claims = await decodeAccessToken(token);
    await asAuthenticated(client, claims.sub, async () => {
      const { rows } = await client.query<{ user_id: string; organization_id: string }>(
        `select user_id, organization_id
           from public.memberships
          where organization_id = $1
          order by user_id asc`,
        [SEED_IDS.alphaOrg],
      );
      // All 5 Alpha memberships visible (the suspended one too — that's the
      // members list endpoint's job to filter by RLS visibility, not ours).
      const userIds = rows.map((r) => r.user_id).sort();
      expect(userIds).toEqual(
        [
          SEED_IDS.alphaAdmin,
          SEED_IDS.alphaManager,
          SEED_IDS.alphaSuspended,
          SEED_IDS.alphaUserA,
          SEED_IDS.alphaUserB,
        ].sort(),
      );
    });
  });

  it('cross-tenant membership SELECT returns 0 rows (RLS hides foreign tenant)', async () => {
    const token = await signIn(SEED_IDENTITIES.betaAdmin);
    const claims = await decodeAccessToken(token);
    await asAuthenticated(client, claims.sub, async () => {
      const { rows } = await client.query<{ id: string }>(
        `select id from public.memberships where organization_id = $1`,
        [SEED_IDS.alphaOrg],
      );
      expect(rows).toEqual([]);
    });
  });

  it('memberships_select_self returns caller own row even when suspended', async () => {
    const token = await signIn(SEED_IDENTITIES.alphaSuspended);
    const claims = await decodeAccessToken(token);
    await asAuthenticated(client, claims.sub, async () => {
      // The self-select policy must return the suspended row so the Nest
      // layer can distinguish a known suspended caller (403) from a missing
      // membership (404).
      const { rows } = await client.query<{ user_id: string; status: string }>(
        `select user_id, status
           from public.memberships
          where organization_id = $1 and user_id = $2`,
        [SEED_IDS.alphaOrg, SEED_IDS.alphaSuspended],
      );
      expect(rows).toEqual([
        { user_id: SEED_IDS.alphaSuspended, status: 'suspended' },
      ]);
    });
  });
});

describe('Task 6: membership updates + last-admin trigger', () => {
  let client: Client;
  beforeAll(async () => {
    client = new Client({ connectionString });
    await client.connect();
  });
  afterAll(async () => { await client.end(); });

  async function createOrgWithAdmin(
    role: 'user' | 'manager' | 'organization_admin',
  ): Promise<{ orgId: string; userId: string }> {
    const { rows: orgRows } = await client.query<{ id: string }>(
      `insert into public.organizations (name) values ('Task6 Org') returning id`,
    );
    const orgId = orgRows[0].id;
    const { rows: userRows } = await client.query<{ id: string }>(
      `insert into auth.users (id, email, encrypted_password) values (gen_random_uuid()::uuid, gen_random_uuid()::text||'@test.com', '$2a$10$x') returning id`,
    );
    const userId = userRows[0].id;
    await client.query(
      `insert into public.profiles (user_id, display_name) values ($1, $2)`,
      [userId, `T6 ${role}`],
    );
    await client.query(
      `insert into public.memberships (organization_id, user_id, role, status)
       values ($1, $2, $3, 'active')`,
      [orgId, userId, role],
    );
    return { orgId, userId };
  }

  it('active organization_admin can update another membership in same tenant', async () => {
    const { orgId, userId: adminId } = await createOrgWithAdmin('organization_admin');
    const { userId: targetUserId } = await createOrgWithAdmin('user');
    // Add targetUserId to the admin's org as a plain user.
    await client.query(
      `insert into public.memberships (organization_id, user_id, role, status)
       values ($1, $2, 'user', 'active')`,
      [orgId, targetUserId],
    );
    await asAuthenticated(client, adminId, async () => {
      const { rowCount } = await client.query(
        `update public.memberships set role = 'manager'
          where organization_id = $1 and user_id = $2`,
        [orgId, targetUserId],
      );
      expect(rowCount).toBe(1);
      // Verify the change is visible within the same transaction.
      const { rows } = await client.query<{ role: string }>(
        `select role from public.memberships
          where organization_id = $1 and user_id = $2`,
        [orgId, targetUserId],
      );
      expect(rows[0].role).toBe('manager');
    });
  });

  it('user role UPDATE in own tenant is silently filtered by RLS (rowCount=0)', async () => {
    const { orgId, userId } = await createOrgWithAdmin('user');
    const { userId: targetId } = await createOrgWithAdmin('user');
    await client.query(
      `insert into public.memberships (organization_id, user_id, role, status)
       values ($1, $2, 'user', 'active')`,
      [orgId, targetId],
    );
    await asAuthenticated(client, userId, async () => {
      // memberships_update_admin USING requires 'organization_admin'; a 'user'
      // caller fails the predicate, so the WHERE clause matches 0 rows.
      // UPDATE returns success but no rows change. RLS does NOT throw — it
      // filters. The Nest layer is the first defense (it 403s on role).
      const { rowCount } = await client.query(
        `update public.memberships set role = 'manager'
          where organization_id = $1 and user_id = $2`,
        [orgId, targetId],
      );
      expect(rowCount).toBe(0);
    });
    const { rows } = await client.query<{ role: string }>(
      `select role from public.memberships
        where organization_id = $1 and user_id = $2`,
      [orgId, targetId],
    );
    expect(rows[0].role).toBe('user');
  });

  it('suspended caller UPDATE is silently filtered by RLS (rowCount=0)', async () => {
    const { orgId, userId: adminId } = await createOrgWithAdmin('organization_admin');
    const { userId: suspendedId } = await createOrgWithAdmin('user');
    // Move suspendedId into the admin's org and suspend them there.
    await client.query(
      `delete from public.memberships where user_id = $1`,
      [suspendedId],
    );
    await client.query(
      `insert into public.memberships (organization_id, user_id, role, status)
       values ($1, $2, 'user', 'suspended')`,
      [orgId, suspendedId],
    );
    void adminId;
    await asAuthenticated(client, suspendedId, async () => {
      const { rowCount } = await client.query(
        `update public.memberships set status = 'active'
          where organization_id = $1 and user_id = $2`,
        [orgId, suspendedId],
      );
      expect(rowCount).toBe(0);
    });
  });

  it('cross-tenant UPDATE via RLS-context returns 0 rows (RLS hides foreign tenant before any check)', async () => {
    const { orgId: foreignOrg } = await createOrgWithAdmin('organization_admin');
    const { userId: foreignAdmin } = await createOrgWithAdmin('user');
    await client.query(
      `update public.memberships set organization_id = $1, user_id = $2
       where organization_id = $1 and user_id = $2`,
      [foreignOrg, foreignAdmin],
    );
    void foreignAdmin;
    // Active admin in their own org tries to update a membership in foreign
    // org. RLS hides the foreign row, so UPDATE matches 0 rows; client sees
    // success but row unchanged.
    const { orgId: ownOrg } = await createOrgWithAdmin('organization_admin');
    const { rows: ownAdminRows } = await client.query<{ user_id: string }>(
      `select user_id from public.memberships
        where organization_id = $1 and role = 'organization_admin'`,
      [ownOrg],
    );
    const ownAdminId = ownAdminRows[0].user_id;
    await asAuthenticated(client, ownAdminId, async () => {
      const { rowCount } = await client.query(
        `update public.memberships set role = 'manager'
          where organization_id = $1`,
        [foreignOrg],
      );
      expect(rowCount).toBe(0);
    });
  });

  it('final-admin self-demotion blocked by enforce_last_admin() trigger', async () => {
    const { orgId, userId } = await createOrgWithAdmin('organization_admin');
    await expect(
      client.query(
        `update public.memberships set role = 'manager'
          where organization_id = $1 and user_id = $2`,
        [orgId, userId],
      ),
    ).rejects.toMatchObject({ message: expect.stringMatching(/last_admin/) });
  });

  it('final-admin self-suspension blocked by enforce_last_admin() trigger', async () => {
    const { orgId, userId } = await createOrgWithAdmin('organization_admin');
    await expect(
      client.query(
        `update public.memberships set status = 'suspended'
          where organization_id = $1 and user_id = $2`,
        [orgId, userId],
      ),
    ).rejects.toMatchObject({ message: expect.stringMatching(/last_admin/) });
  });

  it('two-admin race: exactly one demotion succeeds, the other raises last_admin', async () => {
    const { orgId } = await createOrgWithAdmin('organization_admin');
    const { userId: secondAdmin } = await createOrgWithAdmin('organization_admin');
    await client.query(
      `insert into public.memberships (organization_id, user_id, role, status)
       values ($1, $2, 'organization_admin', 'active')`,
      [orgId, secondAdmin],
    );
    const { rows: aRows } = await client.query<{ user_id: string }>(
      `select user_id from public.memberships
        where organization_id = $1 and role = 'organization_admin' and status = 'active'
        order by user_id asc limit 1`,
      [orgId],
    );
    const firstAdmin = aRows[0].user_id;
    const otherAdmin =
      firstAdmin === secondAdmin
        ? (await client.query<{ user_id: string }>(
            `select user_id from public.memberships
              where organization_id = $1 and role = 'organization_admin' and status = 'active'
              order by user_id desc limit 1`,
            [orgId],
          )).rows[0].user_id
        : secondAdmin;

    // Run both demotions in two separate pg clients in parallel; one must
    // succeed, the other must fail with last_admin (P0001).
    const c1 = new Client({ connectionString });
    const c2 = new Client({ connectionString });
    await Promise.all([c1.connect(), c2.connect()]);
    try {
      const tx1 = c1
        .query('begin')
        .then(() => c1.query(`update public.memberships set role = 'manager' where user_id = $1`, [firstAdmin]))
        .then(() => c1.query('commit'))
        .then(() => 'ok' as const)
        .catch((err: unknown) => {
          void c1.query('rollback').catch(() => {});
          return err instanceof Error && /last_admin/.test(err.message)
            ? ('last_admin' as const)
            : Promise.reject(err);
        });
      const tx2 = c2
        .query('begin')
        .then(() => c2.query(`update public.memberships set role = 'manager' where user_id = $1`, [otherAdmin]))
        .then(() => c2.query('commit'))
        .then(() => 'ok' as const)
        .catch((err: unknown) => {
          void c2.query('rollback').catch(() => {});
          return err instanceof Error && /last_admin/.test(err.message)
            ? ('last_admin' as const)
            : Promise.reject(err);
        });
      const outcomes = await Promise.all([tx1, tx2]);
      // Exactly one ok and one last_admin.
      expect(outcomes.filter((o) => o === 'ok')).toHaveLength(1);
      expect(outcomes.filter((o) => o === 'last_admin')).toHaveLength(1);
    } finally {
      await c1.end().catch(() => {});
      await c2.end().catch(() => {});
    }
  });
});

// ----------------------------------------------------------------------------
// Task 7 — invoice ownership + state transitions + allowlists.
// Uses the deterministic seed (alphaUserA owns an Alpha draft,
// alphaUserB owns an Alpha issued; betaAdmin owns a Beta issued). All
// queries run under SET LOCAL role authenticated with the caller's JWT
// claims, exactly as the caller-scoped Supabase client does in prod.
// ----------------------------------------------------------------------------

describe('Task 7: invoice ownership + state (RLS)', () => {
  let client: Client;

  beforeAll(async () => {
    client = new Client({ connectionString });
    await client.connect();
  });
  afterAll(async () => { await client.end(); });

  it('active user A sees own Alpha invoice and Alpha issued invoice as owner', async () => {
    const token = await signIn(SEED_IDENTITIES.alphaUserA);
    const claims = await decodeAccessToken(token);
    await asAuthenticated(client, claims.sub, async () => {
      const { rows } = await client.query<{ id: string }>(
        `select id from public.invoices where organization_id = $1 order by id asc`,
        [SEED_IDS.alphaOrg],
      );
      // alphaUserA owns the Alpha draft; the Alpha issued invoice is
      // hidden by RLS (owner_id ≠ auth.uid() and role is `user`).
      expect(rows.map((r) => r.id)).toEqual([SEED_IDS.alphaUserAInvoiceDraft]);
    });
  });

  it('active manager sees all Alpha invoices (org-wide visibility)', async () => {
    const token = await signIn(SEED_IDENTITIES.alphaManager);
    const claims = await decodeAccessToken(token);
    await asAuthenticated(client, claims.sub, async () => {
      const { rows } = await client.query<{ id: string }>(
        `select id from public.invoices where organization_id = $1 order by id asc`,
        [SEED_IDS.alphaOrg],
      );
      const ids = rows.map((r) => r.id).sort();
      expect(ids).toEqual(
        [SEED_IDS.alphaUserAInvoiceDraft, SEED_IDS.alphaUserBInvoiceIssued].sort(),
      );
    });
  });

  it('active admin sees all Alpha invoices (org-wide visibility)', async () => {
    const token = await signIn(SEED_IDENTITIES.alphaAdmin);
    const claims = await decodeAccessToken(token);
    await asAuthenticated(client, claims.sub, async () => {
      const { rows } = await client.query<{ id: string }>(
        `select id from public.invoices where organization_id = $1 order by id asc`,
        [SEED_IDS.alphaOrg],
      );
      const ids = rows.map((r) => r.id).sort();
      expect(ids).toEqual(
        [SEED_IDS.alphaUserAInvoiceDraft, SEED_IDS.alphaUserBInvoiceIssued].sort(),
      );
    });
  });

  it('cross-tenant: alpha user SELECTing Beta invoice is hidden (0 rows)', async () => {
    const token = await signIn(SEED_IDENTITIES.alphaUserA);
    const claims = await decodeAccessToken(token);
    await asAuthenticated(client, claims.sub, async () => {
      const { rows } = await client.query<{ id: string }>(
        `select id from public.invoices where id = $1`,
        [SEED_IDS.betaAdminInvoice],
      );
      expect(rows).toEqual([]);
    });
  });

  it('user A INSERTing an invoice sets owner_id from auth.uid() (DB-derived default)', async () => {
    // Reset the user's own session and INSERT one — owner_id is not in the
    // INSERT column grant; it must be defaulted via auth.uid(). This proves
    // the API doesn't need to send owner_id and direct PostgREST cannot
    // override it.
    const token = await signIn(SEED_IDENTITIES.alphaUserA);
    const claims = await decodeAccessToken(token);
    await expect(
      asAuthenticated(client, claims.sub, async () => {
        // The user role is `user`; invoices_insert_manager requires
        // manager|organization_admin. RLS rejects the INSERT.
        await client.query(
          `insert into public.invoices
             (organization_id, customer_id, description, amount_minor, currency)
           values ($1, 'cust', 'desc', 100, 'USD')`,
          [SEED_IDS.alphaOrg],
        );
      }),
    ).rejects.toMatchObject({ code: '42501' });
  });

  it('manager INSERTing an invoice succeeds; owner_id is auth.uid()', async () => {
    const token = await signIn(SEED_IDENTITIES.alphaManager);
    const claims = await decodeAccessToken(token);
    await asAuthenticated(client, claims.sub, async () => {
      const { rows } = await client.query<{ owner_id: string }>(
        `insert into public.invoices
           (organization_id, customer_id, description, amount_minor, currency)
         values ($1, 'cust-x', 'desc-x', 500, 'USD')
         returning owner_id`,
        [SEED_IDS.alphaOrg],
      );
      expect(rows[0].owner_id).toBe(SEED_IDS.alphaManager);
    });
  });

  it('UPDATE setting status to paid for an already-paid invoice is a no-op (self-transition allowed)', async () => {
    // asSuperuserTx rolls back at the end so we can't observe the change
    // across queries. Instead, drive the UPDATE inside an explicit
    // transaction and query within the same transaction before commit.
    await client.query('begin');
    try {
      // First move issued → paid.
      await client.query(
        `update public.invoices set status = 'paid' where id = $1`,
        [SEED_IDS.alphaUserBInvoiceIssued],
      );
      // Now self-transition paid → paid: trigger is no-op.
      await client.query(
        `update public.invoices set status = 'paid' where id = $1`,
        [SEED_IDS.alphaUserBInvoiceIssued],
      );
      const { rows } = await client.query<{ status: string }>(
        `select status from public.invoices where id = $1`,
        [SEED_IDS.alphaUserBInvoiceIssued],
      );
      expect(rows[0].status).toBe('paid');
    } finally {
      await client.query('rollback');
    }
  });

  it('paid → cancelled is rejected by trigger (invalid_state, P0001)', async () => {
    // Drive the UPDATE inside a transaction so the trigger fires; rollback
    // regardless of outcome.
    await client.query('begin');
    let thrown: unknown;
    try {
      await client.query(
        `update public.invoices set status = 'paid' where id = $1`,
        [SEED_IDS.alphaUserBInvoiceIssued],
      );
      try {
        await client.query(
          `update public.invoices set status = 'cancelled' where id = $1`,
          [SEED_IDS.alphaUserBInvoiceIssued],
        );
      } catch (err) {
        thrown = err;
      }
    } finally {
      await client.query('rollback');
    }
    expect(thrown).toMatchObject({ message: expect.stringMatching(/invalid_state/) });
  });

  it('issued → draft is rejected by trigger (invalid_state, P0001)', async () => {
    await client.query('begin');
    let thrown: unknown;
    try {
      // alphaUserAInvoiceDraft starts at 'draft'; first move to 'issued',
      // then try issued → draft. Both within one transaction so the
      // intermediate state is visible to the trigger.
      await client.query(
        `update public.invoices set status = 'issued' where id = $1`,
        [SEED_IDS.alphaUserAInvoiceDraft],
      );
      try {
        await client.query(
          `update public.invoices set status = 'draft' where id = $1`,
          [SEED_IDS.alphaUserAInvoiceDraft],
        );
      } catch (err) {
        thrown = err;
      }
    } finally {
      await client.query('rollback');
    }
    expect(thrown).toMatchObject({ message: expect.stringMatching(/invalid_state/) });
  });

  it('CHECK constraint: amount_minor = 9007199254740991 is accepted', async () => {
    await asSuperuserTx(client, async () => {
      // 9007199254740991 is exactly Number.MAX_SAFE_INTEGER in JS.
      const { rows } = await client.query<{ amount_minor: string }>(
        `update public.invoices set amount_minor = 9007199254740991 where id = $1 returning amount_minor`,
        [SEED_IDS.alphaUserAInvoiceDraft],
      );
      expect(rows[0].amount_minor).toBe('9007199254740991');
    });
  });

  it('CHECK constraint: amount_minor = 9007199254740992 is rejected (23514)', async () => {
    await expect(
      client.query(
        `update public.invoices set amount_minor = 9007199254740992 where id = $1`,
        [SEED_IDS.alphaUserAInvoiceDraft],
      ),
    ).rejects.toMatchObject({ code: '23514' });
  });

  it('CHECK constraint: currency = USDD is rejected (22001 char(3) truncation)', async () => {
    await expect(
      client.query(
        `update public.invoices set currency = 'USDD' where id = $1`,
        [SEED_IDS.alphaUserAInvoiceDraft],
      ),
    ).rejects.toMatchObject({ code: '22001' });
  });
});

// ----------------------------------------------------------------------------
// Task 7 — invoice visibility, ownership, and RLS-denied writes.
// Exercises the existing invoices_select_visible, invoices_insert_manager,
// invoices_update_manager policies. The Postgres trigger
// enforce_invoice_state_transition() is also covered at the SQL boundary.
// ----------------------------------------------------------------------------

describe('Task 7: invoice visibility', () => {
  let client: Client;
  let orgId: string;
  let userAId: string;
  let userBId: string;
  let managerId: string;
  let invoiceOwnedByA: string;
  let invoiceOwnedByB: string;

  beforeAll(async () => {
    client = new Client({ connectionString });
    await client.connect();
    const { rows: orgRows } = await client.query<{ id: string }>(
      `insert into public.organizations (name) values ('Task7 Org') returning id`,
    );
    orgId = orgRows[0].id;

    async function mkUser(role: 'user' | 'manager'): Promise<string> {
      const { rows } = await client.query<{ id: string }>(
        `insert into auth.users (id, email, encrypted_password) values (gen_random_uuid()::uuid, gen_random_uuid()::text||'@test.com', '$2a$10$x') returning id`,
      );
      const id = rows[0].id;
      await client.query(
        `insert into public.profiles (user_id, display_name) values ($1, $2)`,
        [id, `T7 ${role}`],
      );
      await client.query(
        `insert into public.memberships (organization_id, user_id, role, status)
         values ($1, $2, $3, 'active')`,
        [orgId, id, role],
      );
      return id;
    }

    userAId = await mkUser('user');
    userBId = await mkUser('user');
    managerId = await mkUser('manager');

    async function mkInvoice(ownerId: string): Promise<string> {
      const { rows } = await client.query<{ id: string }>(
        `insert into public.invoices
           (organization_id, owner_id, customer_id, description, amount_minor, currency, status)
         values ($1, $2, 'cust', 'desc', 1000, 'USD', 'draft')
         returning id`,
        [orgId, ownerId],
      );
      return rows[0].id;
    }

    invoiceOwnedByA = await mkInvoice(userAId);
    invoiceOwnedByB = await mkInvoice(userBId);
  });
  afterAll(async () => { await client.end(); });

  it('active user sees ONLY own invoice (invoices_select_visible: user branch)', async () => {
    await asAuthenticated(client, userAId, async () => {
      const { rows } = await client.query<{ id: string }>(
        `select id from public.invoices where organization_id = $1 order by id asc`,
        [orgId],
      );
      expect(rows.map((r) => r.id)).toEqual([invoiceOwnedByA]);
    });
  });

  it("active user sees 0 rows for another user's invoice", async () => {
    await asAuthenticated(client, userAId, async () => {
      const { rows } = await client.query<{ id: string }>(
        `select id from public.invoices where id = $1`,
        [invoiceOwnedByB],
      );
      expect(rows).toEqual([]);
    });
  });

  it('manager sees all invoices in the organization (invoices_select_visible: manager branch)', async () => {
    await asAuthenticated(client, managerId, async () => {
      const { rows } = await client.query<{ id: string }>(
        `select id from public.invoices where organization_id = $1 order by id asc`,
        [orgId],
      );
      expect(rows.map((r) => r.id).sort()).toEqual(
        [invoiceOwnedByA, invoiceOwnedByB].sort(),
      );
    });
  });

  it("user UPDATE on another user's invoice matches 0 rows (RLS filters via USING)", async () => {
    await asAuthenticated(client, userAId, async () => {
      const { rowCount } = await client.query(
        `update public.invoices set status = 'issued' where id = $1`,
        [invoiceOwnedByB],
      );
      expect(rowCount).toBe(0);
    });
  });
});

describe('Task 7: invoice insert RLS', () => {
  let client: Client;
  let orgId: string;
  let userId: string;
  let managerId: string;

  beforeAll(async () => {
    client = new Client({ connectionString });
    await client.connect();
    const { rows: orgRows } = await client.query<{ id: string }>(
      `insert into public.organizations (name) values ('Task7 Insert') returning id`,
    );
    orgId = orgRows[0].id;
    async function mkUser(role: 'user' | 'manager'): Promise<string> {
      const { rows } = await client.query<{ id: string }>(
        `insert into auth.users (id, email, encrypted_password) values (gen_random_uuid()::uuid, gen_random_uuid()::text||'@test.com', '$2a$10$x') returning id`,
      );
      const id = rows[0].id;
      await client.query(
        `insert into public.profiles (user_id, display_name) values ($1, $2)`,
        [id, `T7i ${role}`],
      );
      await client.query(
        `insert into public.memberships (organization_id, user_id, role, status)
         values ($1, $2, $3, 'active')`,
        [orgId, id, role],
      );
      return id;
    }
    userId = await mkUser('user');
    managerId = await mkUser('manager');
  });
  afterAll(async () => { await client.end(); });

  it('user INSERT is rejected by RLS WITH CHECK (policy violation)', async () => {
    // Unlike SELECT/UPDATE (which silently filter via USING), INSERT with a
    // failing WITH CHECK throws "new row violates row-level security policy".
    // The error code is 42501 (insufficient_privilege). Nest maps this to
    // 403 forbidden or 404 not_found depending on the service layer.
    await expect(
      asAuthenticated(client, userId, async () => {
        await client.query(
          `insert into public.invoices
             (organization_id, customer_id, description, amount_minor, currency)
           values ($1, 'cust', 'desc', 100, 'USD')`,
          [orgId],
        );
      }),
    ).rejects.toMatchObject({ code: '42501' });
  });

  it('manager INSERT succeeds and DB defaults owner_id = auth.uid(), status = draft', async () => {
    await asAuthenticated(client, managerId, async () => {
      const { rows } = await client.query<{ owner_id: string; status: string }>(
        `insert into public.invoices
           (organization_id, customer_id, description, amount_minor, currency)
         values ($1, 'cust', 'desc', 100, 'USD')
         returning owner_id, status`,
        [orgId],
      );
      expect(rows[0].owner_id).toBe(managerId);
      expect(rows[0].status).toBe('draft');
    });
  });

  it('insert with privileged fields (owner_id, organization_id) is rejected by column grant', async () => {
    // Spec §6.2: owner_id column is not granted to `authenticated`. INSERT
    // attempting to set owner_id is rejected with 42501.
    await expect(
      asAuthenticated(client, managerId, async () => {
        await client.query(
          `insert into public.invoices
             (organization_id, owner_id, customer_id, description, amount_minor, currency)
           values ($1, $2, 'cust', 'desc', 100, 'USD')`,
          [orgId, managerId],
        );
      }),
    ).rejects.toMatchObject({ code: '42501' });
  });
});

// ----------------------------------------------------------------------------
// Task 9 — definer role, grants, ownership, RLS policies, and the
// `public.create_refund` RPC. Asserts the privilege inventory, the
// function-level hardening (owner, empty search_path, narrow grants), the
// rejection matrix (same-org `user` → forbidden; foreign invoice → not_found;
// idempotent replay vs conflict; concurrent over-refund cap), and the
// atomic success-audit behavior.
// ----------------------------------------------------------------------------

describe('Task 9: definer role attributes', () => {
  let client: Client;
  beforeAll(async () => {
    client = new Client({ connectionString });
    await client.connect();
  });
  afterAll(async () => { await client.end(); });

  it('public_refund_definer exists with nologin, noinherit, nobypassrls', async () => {
    const { rows } = await client.query<{
      rolname: string;
      rolcanlogin: boolean;
      rolinherit: boolean;
      rolbypassrls: boolean;
      rolsuper: boolean;
      rolreplication: boolean;
    }>(
      `select rolname, rolcanlogin, rolinherit, rolbypassrls, rolsuper, rolreplication
         from pg_roles
        where rolname = 'public_refund_definer'`,
    );
    expect(rows).toHaveLength(1);
    expect(rows[0]).toEqual({
      rolname: 'public_refund_definer',
      rolcanlogin: false,
      rolinherit: false,
      rolbypassrls: false,
      rolsuper: false,
      rolreplication: false,
    });
  });

  it('public_refund_definer is NOT a member of service_role', async () => {
    const { rows } = await client.query<{ count: string }>(
      `select count(*)::text as count
         from pg_auth_members m
         join pg_roles r on r.oid = m.roleid
         join pg_roles mr on mr.oid = m.member
        where r.rolname = 'service_role'
          and mr.rolname = 'public_refund_definer'`,
    );
    expect(rows[0].count).toBe('0');
  });
});

describe('Task 9: definer-role grants', () => {
  let client: Client;
  beforeAll(async () => {
    client = new Client({ connectionString });
    await client.connect();
  });
  afterAll(async () => { await client.end(); });

  // Compact ACL shape used by information_schema.role_table_grants / role_routine_grants.
  async function hasTableGrant(table: string, privilege: string): Promise<boolean> {
    const { rows } = await client.query<{ count: string }>(
      `select count(*)::text as count
         from information_schema.role_table_grants
        where grantee = 'public_refund_definer'
          and table_schema = 'public'
          and table_name = $1
          and privilege_type = $2`,
      [table, privilege],
    );
    return rows[0].count === '1';
  }

  it('grants SELECT on public.invoices', async () => {
    expect(await hasTableGrant('invoices', 'SELECT')).toBe(true);
  });

  it('grants column UPDATE on invoices.id only (no full-table UPDATE)', async () => {
    // Column-level UPDATE grant on (id) is not exposed via
    // information_schema.role_table_grants (it lists table-level only).
    // Use the catalog directly via has_column_privilege.
    const { rows } = await client.query<{ ok: boolean }>(
      `select has_column_privilege('public_refund_definer', 'public.invoices'::regclass, 'id', 'UPDATE') as ok`,
    );
    expect(rows[0].ok).toBe(true);
  });

  it('grants SELECT on public.memberships', async () => {
    expect(await hasTableGrant('memberships', 'SELECT')).toBe(true);
  });

  it('grants SELECT, INSERT on public.refunds', async () => {
    expect(await hasTableGrant('refunds', 'SELECT')).toBe(true);
    expect(await hasTableGrant('refunds', 'INSERT')).toBe(true);
  });

  it('grants INSERT on public.audit_events', async () => {
    expect(await hasTableGrant('audit_events', 'INSERT')).toBe(true);
  });

  it('grants USAGE on schema auth', async () => {
    const { rows } = await client.query<{ has_usage: boolean }>(
      `select has_schema_privilege('public_refund_definer', 'auth', 'USAGE') as has_usage`,
    );
    expect(rows[0].has_usage).toBe(true);
  });

  it('grants EXECUTE on function auth.uid()', async () => {
    const { rows } = await client.query<{ has_execute: boolean }>(
      `select has_function_privilege(
          'public_refund_definer',
          'auth.uid()'::regprocedure,
          'EXECUTE'
        ) as has_execute`,
    );
    expect(rows[0].has_execute).toBe(true);
  });
});

describe('Task 9: create_refund function hardening', () => {
  let client: Client;
  beforeAll(async () => {
    client = new Client({ connectionString });
    await client.connect();
  });
  afterAll(async () => { await client.end(); });

  it('is owned by public_refund_definer (NOT service_role or postgres)', async () => {
    const { rows } = await client.query<{ proname: string; proowner: string; owner_name: string }>(
      `select p.proname,
              p.proowner::regrole::text as proowner,
              r.rolname as owner_name
         from pg_proc p
         join pg_roles r on r.oid = p.proowner
        where p.proname = 'create_refund'
          and p.pronamespace = 'public'::regnamespace`,
    );
    expect(rows).toHaveLength(1);
    expect(rows[0].owner_name).toBe('public_refund_definer');
  });

  it('proacl does NOT include service_role', async () => {
    // Convert the ACL array to a textual representation; the service_role
    // entry would show up as a grantee name in the ACL string.
    const { rows } = await client.query<{ acl: string }>(
      `select proacl::text as acl
         from pg_proc
        where proname = 'create_refund'
          and pronamespace = 'public'::regnamespace`,
    );
    expect(rows).toHaveLength(1);
    expect(rows[0].acl).not.toMatch(/service[_-]?role/i);
    // PUBLIC must be revoked; only `authenticated` and the definer owner
    // should appear in the ACL.
    expect(rows[0].acl).toMatch(/authenticated=/);
  });

  it('search_path is empty (proconfig contains set search_path = "")', async () => {
    const { rows } = await client.query<{ proconfig: string[] | null }>(
      `select proconfig
         from pg_proc
        where proname = 'create_refund'
          and pronamespace = 'public'::regnamespace`,
    );
    expect(rows).toHaveLength(1);
    const cfg = rows[0].proconfig ?? [];
    // Postgres stores a SET clause as a proconfig entry of the form
    // `search_path=""` (the empty value is wrapped in double quotes
    // inside the proconfig text). A non-empty search_path would
    // instead render as `search_path="public,pg_temp"`. The exact
    // empty-string representation is therefore `search_path=""` —
    // not `search_path=` (which would be malformed) and not
    // `search_path="$user"` (which would inherit from the role).
    const entry = cfg.find((s) => s.startsWith('search_path')) ?? '';
    expect(entry).toBe('search_path=""');
  });
});

describe('Task 9: forced-RLS definer policies', () => {
  let client: Client;
  beforeAll(async () => {
    client = new Client({ connectionString });
    await client.connect();
  });
  afterAll(async () => { await client.end(); });

  // Returns the policy names present on a table for the definer role,
  // restricted to the policy kinds exercised by the function (select,
  // update, insert). `polpermissive` is a boolean, NOT an OID — the role
  // list is in `polroles` (oid[]). For permissive policies targeted at a
  // single role, polroles is the singleton array of that role's oid.
  async function definerPolicies(table: string): Promise<{ policy: string; cmd: string }[]> {
    const { rows } = await client.query<{ polname: string; polcmd: string }>(
      `select polname, polcmd
         from pg_policy p
         join pg_class c on c.oid = p.polrelid
        where c.relname = $1
          and c.relnamespace = 'public'::regnamespace
          and p.polpermissive = true
          and cardinality(p.polroles) = 1
          and p.polroles[1] = (
            select oid from pg_roles where rolname = 'public_refund_definer'
          )`,
      [table],
    );
    return rows.map((r) => ({ policy: r.polname, cmd: r.polcmd }));
  }

  it('refund_definer_select_invoices on public.invoices (SELECT)', async () => {
    const policies = await definerPolicies('invoices');
    expect(policies).toEqual(expect.arrayContaining([
      { policy: 'refund_definer_select_invoices', cmd: 'r' },
      { policy: 'refund_definer_update_invoices_lock', cmd: 'w' },
    ]));
  });

  it('refund_definer_select_memberships on public.memberships (SELECT)', async () => {
    const policies = await definerPolicies('memberships');
    expect(policies).toEqual(expect.arrayContaining([
      { policy: 'refund_definer_select_memberships', cmd: 'r' },
    ]));
  });

  it('refund_definer_select_refunds + refund_definer_insert_refunds on public.refunds', async () => {
    const policies = await definerPolicies('refunds');
    expect(policies).toEqual(expect.arrayContaining([
      { policy: 'refund_definer_select_refunds', cmd: 'r' },
      { policy: 'refund_definer_insert_refunds', cmd: 'a' },
    ]));
  });

  it('refund_definer_insert_audit_success on public.audit_events (INSERT) is narrowly scoped', async () => {
    const policies = await definerPolicies('audit_events');
    expect(policies).toEqual(expect.arrayContaining([
      { policy: 'refund_definer_insert_audit_success', cmd: 'a' },
    ]));
    // The policy's WITH CHECK qual must restrict to refund.created/success.
    const { rows } = await client.query<{ polqual: string; polwithcheck: string }>(
      `select pg_get_expr(p.polqual, p.polrelid) as polqual,
              pg_get_expr(p.polwithcheck, p.polrelid) as polwithcheck
         from pg_policy p
         join pg_class c on c.oid = p.polrelid
        where c.relname = 'audit_events'
          and c.relnamespace = 'public'::regnamespace
          and p.polpermissive = true
          and cardinality(p.polroles) = 1
          and p.polroles[1] = (
            select oid from pg_roles where rolname = 'public_refund_definer'
          )
          and p.polname = 'refund_definer_insert_audit_success'`,
    );
    expect(rows).toHaveLength(1);
    expect(rows[0].polwithcheck).toMatch(/action\s*=\s*'refund\.created'/);
    expect(rows[0].polwithcheck).toMatch(/result\s*=\s*'success'/);
  });
});

describe('Task 9: create_refund RPC — privilege + rejection matrix', () => {
  let client: Client;

  beforeAll(async () => {
    client = new Client({ connectionString });
    await client.connect();
  });
  afterAll(async () => { await client.end(); });

  async function makeOrgWithMembers(): Promise<{
    orgId: string;
    managerId: string;
    userId: string;
    invoiceIssuedId: string;
    invoicePaidId: string;
    invoiceDraftId: string;
    foreignInvoiceId: string;
  }> {
    const { rows: orgRows } = await client.query<{ id: string }>(
      `insert into public.organizations (name) values ('Task9 RPC') returning id`,
    );
    const orgId = orgRows[0].id;

    async function mkUser(role: 'user' | 'manager'): Promise<string> {
      const { rows: uRows } = await client.query<{ id: string }>(
        `insert into auth.users (id, email, encrypted_password) values (gen_random_uuid()::uuid, gen_random_uuid()::text||'@test.com', '$2a$10$x') returning id`,
      );
      const id = uRows[0].id;
      await client.query(
        `insert into public.profiles (user_id, display_name) values ($1, $2)`,
        [id, `T9-${role}`],
      );
      await client.query(
        `insert into public.memberships (organization_id, user_id, role, status)
         values ($1, $2, $3, 'active')`,
        [orgId, id, role],
      );
      return id;
    }
    const managerId = await mkUser('manager');
    const userId = await mkUser('user');

    async function mkInvoice(
      ownerId: string,
      status: 'draft' | 'issued' | 'paid',
      orgIdOverride?: string,
    ): Promise<string> {
      const targetOrg = orgIdOverride ?? orgId;
      const { rows: iRows } = await client.query<{ id: string }>(
        `insert into public.invoices
           (organization_id, owner_id, customer_id, description, amount_minor, currency, status)
         values ($1, $2, 'cust', 'desc', 1000, 'USD', $3)
         returning id`,
        [targetOrg, ownerId, status],
      );
      return iRows[0].id;
    }

    // Foreign invoice lives in a different org; the cross-tenant call from
    // managerId should be hidden by RLS as not_found.
    const { rows: fOrgRows } = await client.query<{ id: string }>(
      `insert into public.organizations (name) values ('Task9 Foreign') returning id`,
    );
    const foreignOrgId = fOrgRows[0].id;
    const foreignInvoiceId = await mkInvoice(managerId, 'issued', foreignOrgId);

    const invoiceIssuedId = await mkInvoice(managerId, 'issued');
    const invoicePaidId = await mkInvoice(managerId, 'paid');
    const invoiceDraftId = await mkInvoice(managerId, 'draft');
    return {
      orgId,
      managerId,
      userId,
      invoiceIssuedId,
      invoicePaidId,
      invoiceDraftId,
      foreignInvoiceId,
    };
  }

  it('same-org `user` role calling create_refund raises `forbidden` (42501)', async () => {
    const { orgId, userId, invoiceIssuedId } = await makeOrgWithMembers();
    await expect(
      asAuthenticated(client, userId, async () => {
        await client.query(
          `select public.create_refund($1::uuid, $2::bigint, $3::char(3), $4::text, $5::text, $6::uuid)`,
          [invoiceIssuedId, 100, 'USD', 'r', 'idem-user-forbidden', '00000000-0000-4000-8000-000000000001'],
        );
      }),
    ).rejects.toMatchObject({ message: expect.stringMatching(/forbidden/) });
  });

  it('foreign invoice raises `not_found` (P0002) — RLS hides cross-tenant existence', async () => {
    const { managerId, foreignInvoiceId } = await makeOrgWithMembers();
    await expect(
      asAuthenticated(client, managerId, async () => {
        await client.query(
          `select public.create_refund($1::uuid, $2::bigint, $3::char(3), $4::text, $5::text, $6::uuid)`,
          [foreignInvoiceId, 100, 'USD', 'r', 'idem-foreign', '00000000-0000-4000-8000-000000000002'],
        );
      }),
    ).rejects.toMatchObject({ message: expect.stringMatching(/not_found/) });
  });

  it('manager happy path on issued invoice persists refund + success audit (correlation_id = p_request_id)', async () => {
    const { orgId, managerId, invoiceIssuedId } = await makeOrgWithMembers();
    const requestId = '11111111-1111-4111-8111-999999999991';
    const idemKey = `idem-happy-${Date.now()}`;
    // Run the call as the manager inside an `authenticated` transaction
    // so the SQL function runs under the right RLS context, then verify
    // the side effects (refund row + audit row) from a separate
    // superuser transaction. The two transactions are independent
    // because we COMMIT the call (no rollback) and then issue separate
    // verification queries under superuser that can read both tables.
    //
    // The `asAuthenticated` helper rolls back at the end of its fn
    // block, which would wipe the create_refund side effects. We use a
    // hand-rolled `begin / commit` block here so the inserts are
    // visible to the verification step. The teardown transaction at
    // the end of the test still cleans up the data.
    let refundId = '';
    await client.query('begin');
    try {
      await client.query(`set local role authenticated`);
      await client.query(`set local "request.jwt.claim.sub" = '${managerId}'`);
      await client.query(`set local "request.jwt.claim.role" = 'authenticated'`);
      const { rows } = await client.query<{ id: string }>(
        `select (public.create_refund($1::uuid, $2::bigint, $3::char(3), $4::text, $5::text, $6::uuid)).id as id`,
        [invoiceIssuedId, 200, 'USD', 'partial refund', idemKey, requestId],
      );
      refundId = rows[0].id;
      await client.query('commit');
    } catch (e) {
      await client.query('rollback');
      throw e;
    }

    // Verification runs under superuser so it can read both refunds and
    // audit_events (the latter is restricted to the service role per
    // Spec §6.2). The data was just committed; the rollback that
    // eventually happens is in the test's afterAll teardown.
    const { rows: refundRows } = await client.query<{
      amount_minor: string;
      currency: string;
      idempotency_key: string;
      organization_id: string;
      created_by: string;
    }>(
      `select amount_minor::text, currency, idempotency_key, organization_id, created_by
         from public.refunds where id = $1`,
      [refundId],
    );
    expect(refundRows).toHaveLength(1);
    expect(refundRows[0].amount_minor).toBe('200');
    expect(refundRows[0].currency).toBe('USD');
    expect(refundRows[0].idempotency_key).toBe(idemKey);
    expect(refundRows[0].organization_id).toBe(orgId);
    expect(refundRows[0].created_by).toBe(managerId);

    const { rows: auditRows } = await client.query<{
      correlation_id: string;
      action: string;
      result: string;
      target_id: string;
      metadata: { invoiceId?: string; amountMinor?: number; currency?: string };
    }>(
      `select correlation_id::text, action, result, target_id, metadata
         from public.audit_events
        where correlation_id = $1`,
      [requestId],
    );
    expect(auditRows).toHaveLength(1);
    expect(auditRows[0].action).toBe('refund.created');
    expect(auditRows[0].result).toBe('success');
    expect(auditRows[0].target_id).toBe(refundId);
    expect(auditRows[0].metadata.invoiceId).toBe(invoiceIssuedId);
    expect(auditRows[0].metadata.amountMinor).toBe(200);
    expect(auditRows[0].metadata.currency).toBe('USD');

    // Clean up the test-scoped data so the schema stays deterministic.
    await client.query(`delete from public.refunds where id = $1`, [refundId]);
    await client.query(`delete from public.audit_events where correlation_id = $1`, [requestId]);
  });

  it('idempotent replay: same key + same payload returns the original (no duplicate refund, no duplicate audit)', async () => {
    const { managerId, invoicePaidId } = await makeOrgWithMembers();
    const requestId1 = '11111111-1111-4111-8111-aaaaaaaaaaaa';
    const requestId2 = '11111111-1111-4111-8111-bbbbbbbbbbbb';
    const idemKey = `idem-replay-${Date.now()}`;
    let originalId = '';
    let replayId = '';
    // Both calls run in a single COMMIT block (asAuthenticated would
    // roll back and wipe the first insert). The function's own PL/pgSQL
    // transaction commits the first insert, then the second call sees
    // it and takes the early-return path.
    await client.query('begin');
    try {
      await client.query(`set local role authenticated`);
      await client.query(`set local "request.jwt.claim.sub" = '${managerId}'`);
      await client.query(`set local "request.jwt.claim.role" = 'authenticated'`);
      const { rows: rows1 } = await client.query<{ id: string }>(
        `select (public.create_refund($1::uuid, $2::bigint, $3::char(3), $4::text, $5::text, $6::uuid)).id as id`,
        [invoicePaidId, 150, 'USD', 'replay test', idemKey, requestId1],
      );
      originalId = rows1[0].id;
      const { rows: rows2 } = await client.query<{ id: string }>(
        `select (public.create_refund($1::uuid, $2::bigint, $3::char(3), $4::text, $5::text, $6::uuid)).id as id`,
        [invoicePaidId, 150, 'USD', 'replay test', idemKey, requestId2],
      );
      replayId = rows2[0].id;
      await client.query('commit');
    } catch (e) {
      await client.query('rollback');
      throw e;
    }

    // The replay must return the original id, not a new one.
    expect(replayId).toBe(originalId);

    // Verification: exactly one refund row exists for this idempotency
    // key. The verification query runs under superuser so RLS does not
    // hide the row from us.
    const { rowCount } = await client.query(
      `select 1 from public.refunds where idempotency_key = $1`,
      [idemKey],
    );
    expect(rowCount).toBe(1);

    // Exactly one success audit with the ORIGINAL correlation_id; the
    // replay's correlation_id is NOT written to audit_events for the
    // successful-replay path.
    const { rows: auditRows } = await client.query<{ correlation_id: string }>(
      `select correlation_id::text from public.audit_events where correlation_id = any($1::uuid[])`,
      [[requestId1, requestId2]],
    );
    const ids = auditRows.map((r) => r.correlation_id);
    expect(ids).toEqual([requestId1]);

    // Clean up the test-scoped data.
    await client.query(`delete from public.refunds where idempotency_key = $1`, [idemKey]);
    await client.query(`delete from public.audit_events where correlation_id = $1`, [requestId1]);
  });

  it('idempotent_conflict: same key + different amount raises idempotency_conflict (40P05)', async () => {
    const { managerId, invoicePaidId } = await makeOrgWithMembers();
    const idemKey = `idem-conflict-${Date.now()}`;
    // Both calls run in a single commit block (asAuthenticated would
    // roll back and wipe the first insert). The function's PL/pgSQL
    // transaction commits the first insert, then the second call sees
    // the existing key and raises `idempotency_conflict`.
    let conflictErr: Error | undefined;
    await client.query('begin');
    try {
      await client.query(`set local role authenticated`);
      await client.query(`set local "request.jwt.claim.sub" = '${managerId}'`);
      await client.query(`set local "request.jwt.claim.role" = 'authenticated'`);
      await client.query(
        `select public.create_refund($1::uuid, $2::bigint, $3::char(3), $4::text, $5::text, $6::uuid)`,
        [invoicePaidId, 100, 'USD', 'first', idemKey, '00000000-0000-4000-8000-000000000003'],
      );
      try {
        await client.query(
          `select public.create_refund($1::uuid, $2::bigint, $3::char(3), $4::text, $5::text, $6::uuid)`,
          [invoicePaidId, 200, 'USD', 'first', idemKey, '00000000-0000-4000-8000-000000000004'],
        );
      } catch (err) {
        conflictErr = err as Error;
      }
      await client.query('commit');
    } catch (e) {
      await client.query('rollback');
      throw e;
    }
    expect(conflictErr).toBeDefined();
    expect(conflictErr?.message).toMatch(/idempotency_conflict/);

    // Clean up the test-scoped data. The first call's refund row
    // and audit row are still in the database because we committed.
    await client.query(`delete from public.refunds where idempotency_key = $1`, [idemKey]);
    await client.query(
      `delete from public.audit_events where correlation_id = $1`,
      ['00000000-0000-4000-8000-000000000003'],
    );
  });

  it('cumulative cap: two concurrent refunds that sum > invoice amount → one succeeds, one returns over_refund', async () => {
    const { managerId, invoicePaidId } = await makeOrgWithMembers();
    // invoicePaidId has amount_minor=1000; commit two concurrent refunds
    // each of 700 that together exceed 1000. The SELECT ... FOR UPDATE on
    // the invoice row serializes them: the second waits, re-sums, and is
    // rejected with over_refund.
    const c1 = new Client({ connectionString });
    const c2 = new Client({ connectionString });
    await Promise.all([c1.connect(), c2.connect()]);
    try {
      // Configure both clients as the same authenticated caller so the
      // function is invoked under the manager's identity.
      async function callCreateRefund(client: Client, key: string): Promise<'ok' | 'over_refund'> {
        await client.query('begin');
        try {
          await client.query(`set local role authenticated`);
          await client.query(`set local "request.jwt.claim.sub" = '${managerId}'`);
          await client.query(`set local "request.jwt.claim.role" = 'authenticated'`);
          await client.query(
            `select public.create_refund($1::uuid, $2::bigint, $3::char(3), $4::text, $5::text, $6::uuid)`,
            [invoicePaidId, 700, 'USD', 'concurrent', key, '00000000-0000-4000-8000-000000000005'],
          );
          await client.query('commit');
          return 'ok';
        } catch (err) {
          await client.query('rollback').catch(() => {});
          return err instanceof Error && /over_refund/.test(err.message)
            ? 'over_refund'
            : Promise.reject(err);
        }
      }
      const idemKey1 = `idem-cap-1-${Date.now()}`;
      const idemKey2 = `idem-cap-2-${Date.now()}`;
      const outcomes = await Promise.all([
        callCreateRefund(c1, idemKey1),
        callCreateRefund(c2, idemKey2),
      ]);
      // Exactly one ok and one over_refund.
      expect(outcomes.filter((o) => o === 'ok')).toHaveLength(1);
      expect(outcomes.filter((o) => o === 'over_refund')).toHaveLength(1);
      // Total refunds on the invoice never exceed the invoice amount (1000).
      const { rows } = await client.query<{ total: string }>(
        `select coalesce(sum(amount_minor), 0)::text as total
           from public.refunds where invoice_id = $1`,
        [invoicePaidId],
      );
      expect(Number(rows[0].total)).toBeLessThanOrEqual(1000);
    } finally {
      await c1.end().catch(() => {});
      await c2.end().catch(() => {});
    }
  });

  it('direct INSERT into public.refunds as authenticated is denied (42501)', async () => {
    const { managerId, invoiceIssuedId } = await makeOrgWithMembers();
    await expect(
      asAuthenticated(client, managerId, async () => {
        await client.query(
          `insert into public.refunds (invoice_id, organization_id, created_by, amount_minor, currency, reason, idempotency_key)
           values ($1, gen_random_uuid(), gen_random_uuid(), 100, 'USD', 'r', 'k')`,
          [invoiceIssuedId],
        );
      }),
    ).rejects.toMatchObject({ code: '42501' });
  });
});
