import { execSync } from 'node:child_process';
import { Client } from 'pg';
import { SEED_IDENTITIES, SEED_IDS } from './helpers/seed-identities';
import { signIn, visibleInvoiceIds, decodeAccessToken } from './helpers/auth';
import { closePool } from './helpers/db';

const connectionString = process.env.SUPABASE_DB_URL ?? process.env.DATABASE_URL;
if (!connectionString) throw new Error('SUPABASE_DB_URL (or DATABASE_URL) is required for RLS tests');

const DOMAIN_TABLES = [
  'profiles',
  'organizations',
  'memberships',
  'invoices',
  'refunds',
  'audit_events',
] as const;

// ----------------------------------------------------------------------------
// Role + JWT helpers. SET LOCAL ROLE only lasts for the current transaction,
// so we always BEGIN / ROLLBACK around the boundary. SET LOCAL config keys
// drive auth.uid()/auth.role() via the stub in apps/api/test/sql/000_auth_stub.sql.
// ----------------------------------------------------------------------------
async function asAuthenticated(
  client: Client,
  sub: string,
  fn: () => Promise<void>,
): Promise<void> {
  // NOTE: SET LOCAL does not support extended-query parameter binding, so we
  // interpolate the UUID literal. `sub` is generated by the fixture helper
  // (gen_random_uuid() under superuser), so injection is not a concern.
  await client.query('begin');
  try {
    await client.query(`set local role authenticated`);
    await client.query(`set local "request.jwt.claim.sub" = '${sub}'`);
    await client.query(`set local "request.jwt.claim.role" = 'authenticated'`);
    await fn();
    await client.query('rollback');
  } catch (e) {
    await client.query('rollback');
    throw e;
  }
}

async function asAnon(client: Client, fn: () => Promise<void>): Promise<void> {
  await client.query('begin');
  try {
    await client.query(`set local role anon`);
    await fn();
    await client.query('rollback');
  } catch (e) {
    await client.query('rollback');
    throw e;
  }
}

async function asSuperuserTx(client: Client, fn: () => Promise<void>): Promise<void> {
  await client.query('begin');
  try {
    await fn();
    await client.query('rollback');
  } catch (e) {
    await client.query('rollback');
    throw e;
  }
}

// ----------------------------------------------------------------------------
// Fixture helpers (run as superuser, outside any transaction so rows persist
// across the boundary tests).
// ----------------------------------------------------------------------------
async function createOrg(client: Client): Promise<string> {
  const { rows } = await client.query<{ id: string }>(
    `insert into public.organizations (name) values ('Test Org') returning id`,
  );
  return rows[0].id;
}

async function createUserWithMembership(
  client: Client,
  orgId: string,
  role: 'user' | 'manager' | 'organization_admin',
  status: 'active' | 'suspended' = 'active',
): Promise<string> {
  const { rows } = await client.query<{ id: string }>(
    `insert into auth.users default values returning id`,
  );
  const userId = rows[0].id;
  await client.query(
    `insert into public.profiles (user_id, display_name) values ($1::uuid, $2::text)`,
    [userId, `User ${userId.slice(0, 8)}`],
  );
  await client.query(
    `insert into public.memberships (organization_id, user_id, role, status) values ($1, $2, $3, $4)`,
    [orgId, userId, role, status],
  );
  return userId;
}

async function createInvoice(
  client: Client,
  orgId: string,
  ownerId: string,
  status: 'draft' | 'issued' | 'paid' | 'cancelled' = 'draft',
): Promise<string> {
  const { rows } = await client.query<{ id: string }>(
    `insert into public.invoices
       (organization_id, owner_id, customer_id, description, amount_minor, currency, status)
     values ($1, $2, 'cust-1', 'desc', 1000, 'USD', $3)
     returning id`,
    [orgId, ownerId, status],
  );
  return rows[0].id;
}

// ----------------------------------------------------------------------------
// Tests
// ----------------------------------------------------------------------------
describe('domain schema RLS flags', () => {
  let client: Client;
  beforeAll(async () => {
    client = new Client({ connectionString });
    await client.connect();
  });
  afterAll(async () => { await client.end(); });

  it('every domain table has ENABLE and FORCE ROW LEVEL SECURITY', async () => {
    const { rows } = await client.query<{ relname: string; relrowsecurity: boolean; relforcerowsecurity: boolean }>(
      `select relname, relrowsecurity, relforcerowsecurity
         from pg_class
        where relnamespace = 'public'::regnamespace
          and relkind = 'r'
          and relname in ('profiles','organizations','memberships','invoices','refunds','audit_events')
        order by relname`
    );
    expect(rows).toEqual(expect.arrayContaining([
      expect.objectContaining({ relname: 'audit_events', relrowsecurity: true, relforcerowsecurity: true }),
      expect.objectContaining({ relname: 'invoices',     relrowsecurity: true, relforcerowsecurity: true }),
      expect.objectContaining({ relname: 'memberships',  relrowsecurity: true, relforcerowsecurity: true }),
      expect.objectContaining({ relname: 'organizations',relrowsecurity: true, relforcerowsecurity: true }),
      expect.objectContaining({ relname: 'profiles',     relrowsecurity: true, relforcerowsecurity: true }),
      expect.objectContaining({ relname: 'refunds',      relrowsecurity: true, relforcerowsecurity: true }),
    ]));
  });
});

describe('anon boundary', () => {
  let client: Client;
  beforeAll(async () => {
    client = new Client({ connectionString });
    await client.connect();
  });
  afterAll(async () => { await client.end(); });

  it('health_check() returns true as anon', async () => {
    await asAnon(client, async () => {
      const { rows } = await client.query<{ health_check: boolean }>(
        `select public.health_check() as health_check`,
      );
      expect(rows[0].health_check).toBe(true);
    });
  });

  it.each(DOMAIN_TABLES)('select from public.%s as anon is denied', async (table) => {
    await expect(
      asAnon(client, async () => {
        await client.query(`select * from public.${table}`);
      }),
    ).rejects.toMatchObject({ code: '42501' });
  });
});

describe('authenticated column-write restrictions', () => {
  let client: Client;
  let orgId: string;
  let adminUserId: string;

  beforeAll(async () => {
    client = new Client({ connectionString });
    await client.connect();
    orgId = await createOrg(client);
    adminUserId = await createUserWithMembership(client, orgId, 'organization_admin');
  });
  afterAll(async () => { await client.end(); });

  it('insert into public.refunds as authenticated is denied', async () => {
    await expect(
      asAuthenticated(client, adminUserId, async () => {
        await client.query(
          `insert into public.refunds (invoice_id, organization_id, created_by, amount_minor, currency, reason, idempotency_key)
           values (gen_random_uuid(), gen_random_uuid(), gen_random_uuid(), 100, 'USD', 'r', 'k')`,
        );
      }),
    ).rejects.toMatchObject({ code: '42501' });
  });

  it('insert into public.audit_events as authenticated is denied', async () => {
    await expect(
      asAuthenticated(client, adminUserId, async () => {
        await client.query(
          `insert into public.audit_events (actor_id, organization_id, action, target_type, target_id, result, correlation_id)
           values (gen_random_uuid(), gen_random_uuid(), 'a', 't', '1', 'success', gen_random_uuid())`,
        );
      }),
    ).rejects.toMatchObject({ code: '42501' });
  });

  it('update public.invoices.organization_id as authenticated is denied (column grant covers status only)', async () => {
    const invoiceId = await createInvoice(client, orgId, adminUserId);
    await expect(
      asAuthenticated(client, adminUserId, async () => {
        await client.query(
          `update public.invoices set organization_id = gen_random_uuid() where id = $1`,
          [invoiceId],
        );
      }),
    ).rejects.toMatchObject({ code: '42501' });
  });

  it('update public.invoices.customer_id as authenticated is denied (no UPDATE grant on customer_id)', async () => {
    const invoiceId = await createInvoice(client, orgId, adminUserId);
    await expect(
      asAuthenticated(client, adminUserId, async () => {
        await client.query(
          `update public.invoices set customer_id = 'new-cust' where id = $1`,
          [invoiceId],
        );
      }),
    ).rejects.toMatchObject({ code: '42501' });
  });
});

describe('CHECK constraints on public.invoices', () => {
  let client: Client;
  let orgId: string;
  let ownerId: string;

  beforeAll(async () => {
    client = new Client({ connectionString });
    await client.connect();
    orgId = await createOrg(client);
    ownerId = await createUserWithMembership(client, orgId, 'organization_admin');
  });
  afterAll(async () => { await client.end(); });

  async function expectCheckViolation(makeColumn: string, value: unknown): Promise<void> {
    // Seed one valid invoice per check (the UPDATE is what violates the CHECK).
    const invoiceId = await createInvoice(client, orgId, ownerId);
    await expect(
      client.query(
        `update public.invoices set ${makeColumn} = $1 where id = $2`,
        [value as never, invoiceId],
      ),
    ).rejects.toMatchObject({ code: '23514' });
  }

  it('amount_minor = 0 violates range check', async () => {
    await expectCheckViolation('amount_minor', 0);
  });

  it('amount_minor = 9007199254740992 violates upper bound (bigint max is 9007199254740991)', async () => {
    await expectCheckViolation('amount_minor', '9007199254740992');
  });

  it('amount_minor = -1 violates lower bound', async () => {
    await expectCheckViolation('amount_minor', -1);
  });

  it("currency = 'usd' violates ^[A-Z]{3}$ check", async () => {
    await expectCheckViolation('currency', 'usd');
  });

  it("currency = 'US' violates length-3 check", async () => {
    await expectCheckViolation('currency', 'US');
  });

  it("currency = 'USDD' is rejected (22001 string_data_right_truncation from char(3) cast — fires before the CHECK)", async () => {
    const invoiceId = await createInvoice(client, orgId, ownerId);
    await expect(
      client.query(
        `update public.invoices set currency = $1 where id = $2`,
        ['USDD', invoiceId],
      ),
    ).rejects.toMatchObject({ code: '22001' });
  });

  it('customer_id = empty string violates char_length >= 1 check', async () => {
    await expectCheckViolation('customer_id', '');
  });

  it('customer_id of 129 chars violates char_length <= 128 check', async () => {
    await expectCheckViolation('customer_id', 'x'.repeat(129));
  });

  it('description = empty string violates char_length >= 1 check', async () => {
    await expectCheckViolation('description', '');
  });
});

describe('invoice state machine trigger', () => {
  let client: Client;
  let orgId: string;
  let ownerId: string;

  beforeAll(async () => {
    client = new Client({ connectionString });
    await client.connect();
    orgId = await createOrg(client);
    ownerId = await createUserWithMembership(client, orgId, 'organization_admin');
  });
  afterAll(async () => { await client.end(); });

  async function expectTransition(
    from: 'draft' | 'issued' | 'paid' | 'cancelled',
    to: 'draft' | 'issued' | 'paid' | 'cancelled',
    shouldSucceed: boolean,
  ): Promise<void> {
    const invoiceId = await createInvoice(client, orgId, ownerId, from);
    if (shouldSucceed) {
      await asSuperuserTx(client, async () => {
        await client.query(
          `update public.invoices set status = $1 where id = $2`,
          [to, invoiceId],
        );
      });
    } else {
      await expect(
        asSuperuserTx(client, async () => {
          await client.query(
            `update public.invoices set status = $1 where id = $2`,
            [to, invoiceId],
          );
        }),
      ).rejects.toMatchObject({ message: expect.stringMatching(/invalid_state/) });
    }
  }

  it('draft -> issued succeeds', () => { return expectTransition('draft', 'issued', true); });
  it('draft -> cancelled succeeds', () => { return expectTransition('draft', 'cancelled', true); });
  it('issued -> paid succeeds', () => { return expectTransition('issued', 'paid', true); });
  it('issued -> cancelled succeeds', () => { return expectTransition('issued', 'cancelled', true); });
  it('paid -> paid succeeds (no-op)', () => { return expectTransition('paid', 'paid', true); });
  it('paid -> cancelled raises invalid_state (P0001)', () => { return expectTransition('paid', 'cancelled', false); });
  it('paid -> issued raises invalid_state (P0001)', () => { return expectTransition('paid', 'issued', false); });
  it('issued -> draft raises invalid_state (P0001)', () => { return expectTransition('issued', 'draft', false); });
});

describe('last-admin trigger', () => {
  let client: Client;

  beforeAll(async () => {
    client = new Client({ connectionString });
    await client.connect();
  });
  afterAll(async () => { await client.end(); });

  it('demoting the sole active admin raises last_admin (P0001)', async () => {
    const orgId = await createOrg(client);
    const adminId = await createUserWithMembership(client, orgId, 'organization_admin');
    await createUserWithMembership(client, orgId, 'user');
    await expect(
      asSuperuserTx(client, async () => {
        await client.query(
          `update public.memberships set role = 'manager' where organization_id = $1 and user_id = $2`,
          [orgId, adminId],
        );
      }),
    ).rejects.toMatchObject({ message: expect.stringMatching(/last_admin/) });
  });

  it('suspending the sole active admin raises last_admin (P0001)', async () => {
    const orgId = await createOrg(client);
    const adminId = await createUserWithMembership(client, orgId, 'organization_admin');
    await createUserWithMembership(client, orgId, 'user');
    await expect(
      asSuperuserTx(client, async () => {
        await client.query(
          `update public.memberships set status = 'suspended' where organization_id = $1 and user_id = $2`,
          [orgId, adminId],
        );
      }),
    ).rejects.toMatchObject({ message: expect.stringMatching(/last_admin/) });
  });

  it('demoting one of two active admins succeeds; demoting the other then raises last_admin', async () => {
    const orgId = await createOrg(client);
    const adminAId = await createUserWithMembership(client, orgId, 'organization_admin');
    await createUserWithMembership(client, orgId, 'organization_admin');
    // Demote adminA — second admin still active, succeeds.
    await asSuperuserTx(client, async () => {
      await client.query(
        `update public.memberships set role = 'manager' where organization_id = $1 and user_id = $2`,
        [orgId, adminAId],
      );
    });
    // Now only one admin remains; suspending them must fail.
    await expect(
      asSuperuserTx(client, async () => {
        await client.query(
          `update public.memberships set status = 'suspended' where organization_id = $1 and role = 'organization_admin' and status = 'active'`,
          [orgId],
        );
      }),
    ).rejects.toMatchObject({ message: expect.stringMatching(/last_admin/) });
  });
});

// ----------------------------------------------------------------------------
// Task 3 — visibility against the deterministic seed (apps/api/test/sql/003_seed.sql).
// These tests require db:seed to have been run. They use caller-scoped RLS
// queries against public.invoices; the shared SELECT policy is `invoices_select_visible`
// which branches on active_membership_role(organization_id).
// ----------------------------------------------------------------------------

describe('seed visibility (Task 3)', () => {
  function runReset(): void {
    // Idempotent: db:seed applies auth stub + schema + seed. Safe to re-run.
    execSync('npm run db:seed -w @continuous-security-demo/api', {
      stdio: 'pipe',
      env: process.env,
    });
  }

  it('alphaUserA signs in and sees only own invoice', async () => {
    const token = await signIn(SEED_IDENTITIES.alphaUserA);
    expect(token.split('.')).toHaveLength(3); // JWT header.payload.signature
    expect(await visibleInvoiceIds(token)).toEqual([SEED_IDS.alphaUserAInvoiceDraft]);
  });

  it('alphaUserB sees own invoice only (issued)', async () => {
    const token = await signIn(SEED_IDENTITIES.alphaUserB);
    expect(await visibleInvoiceIds(token)).toEqual([SEED_IDS.alphaUserBInvoiceIssued]);
  });

  it('alphaManager sees all Alpha invoices', async () => {
    const token = await signIn(SEED_IDENTITIES.alphaManager);
    expect(await visibleInvoiceIds(token).then((arr) => arr.sort())).toEqual(
      [SEED_IDS.alphaUserAInvoiceDraft, SEED_IDS.alphaUserBInvoiceIssued].sort(),
    );
  });

  it('alphaAdmin sees all Alpha invoices', async () => {
    const token = await signIn(SEED_IDENTITIES.alphaAdmin);
    expect(await visibleInvoiceIds(token).then((arr) => arr.sort())).toEqual(
      [SEED_IDS.alphaUserAInvoiceDraft, SEED_IDS.alphaUserBInvoiceIssued].sort(),
    );
  });

  it('alphaSuspended sees no invoices', async () => {
    const token = await signIn(SEED_IDENTITIES.alphaSuspended);
    expect(await visibleInvoiceIds(token)).toEqual([]);
  });

  it('betaAdmin sees only Beta invoice', async () => {
    const token = await signIn(SEED_IDENTITIES.betaAdmin);
    expect(await visibleInvoiceIds(token)).toEqual([SEED_IDS.betaAdminInvoice]);
  });

  it('seed is deterministic across resets', async () => {
    const first = await visibleInvoiceIds(await signIn(SEED_IDENTITIES.alphaManager));
    runReset();
    const second = await visibleInvoiceIds(await signIn(SEED_IDENTITIES.alphaManager));
    expect(second.sort()).toEqual(first.sort());
  });

  afterAll(async () => {
    await closePool();
  });
});

// ----------------------------------------------------------------------------
// Task 6 — organizations + memberships + last-admin enforcement.
// Exercises the existing RLS policies (memberships_select_self,
// memberships_select_tenant, memberships_update_admin) and the
// enforce_last_admin() trigger under real Postgres role + JWT claims.
// ----------------------------------------------------------------------------

describe('Task 6: organization membership reads', () => {
  let client: Client;
  beforeAll(async () => {
    client = new Client({ connectionString });
    await client.connect();
  });
  afterAll(async () => { await client.end(); });

  it('active admin sees own organization row in public.organizations', async () => {
    const token = await signIn(SEED_IDENTITIES.alphaAdmin);
    const claims = await decodeAccessToken(token);
    await asAuthenticated(client, claims.sub, async () => {
      const { rows } = await client.query<{ id: string; name: string }>(
        `select id, name from public.organizations where id = $1`,
        [SEED_IDS.alphaOrg],
      );
      expect(rows).toEqual([{ id: SEED_IDS.alphaOrg, name: 'Alpha' }]);
    });
  });

  it('active admin of Alpha sees only Alpha memberships in own tenant', async () => {
    const token = await signIn(SEED_IDENTITIES.alphaAdmin);
    const claims = await decodeAccessToken(token);
    await asAuthenticated(client, claims.sub, async () => {
      const { rows } = await client.query<{ user_id: string; organization_id: string }>(
        `select user_id, organization_id
           from public.memberships
          where organization_id = $1
          order by user_id asc`,
        [SEED_IDS.alphaOrg],
      );
      // All 5 Alpha memberships visible (the suspended one too — that's the
      // members list endpoint's job to filter by RLS visibility, not ours).
      const userIds = rows.map((r) => r.user_id).sort();
      expect(userIds).toEqual(
        [
          SEED_IDS.alphaAdmin,
          SEED_IDS.alphaManager,
          SEED_IDS.alphaSuspended,
          SEED_IDS.alphaUserA,
          SEED_IDS.alphaUserB,
        ].sort(),
      );
    });
  });

  it('cross-tenant membership SELECT returns 0 rows (RLS hides foreign tenant)', async () => {
    const token = await signIn(SEED_IDENTITIES.betaAdmin);
    const claims = await decodeAccessToken(token);
    await asAuthenticated(client, claims.sub, async () => {
      const { rows } = await client.query<{ id: string }>(
        `select id from public.memberships where organization_id = $1`,
        [SEED_IDS.alphaOrg],
      );
      expect(rows).toEqual([]);
    });
  });

  it('memberships_select_self returns caller own row even when suspended', async () => {
    const token = await signIn(SEED_IDENTITIES.alphaSuspended);
    const claims = await decodeAccessToken(token);
    await asAuthenticated(client, claims.sub, async () => {
      // The self-select policy must return the suspended row so the Nest
      // layer can distinguish a known suspended caller (403) from a missing
      // membership (404).
      const { rows } = await client.query<{ user_id: string; status: string }>(
        `select user_id, status
           from public.memberships
          where organization_id = $1 and user_id = $2`,
        [SEED_IDS.alphaOrg, SEED_IDS.alphaSuspended],
      );
      expect(rows).toEqual([
        { user_id: SEED_IDS.alphaSuspended, status: 'suspended' },
      ]);
    });
  });
});

describe('Task 6: membership updates + last-admin trigger', () => {
  let client: Client;
  beforeAll(async () => {
    client = new Client({ connectionString });
    await client.connect();
  });
  afterAll(async () => { await client.end(); });

  async function createOrgWithAdmin(
    role: 'user' | 'manager' | 'organization_admin',
  ): Promise<{ orgId: string; userId: string }> {
    const { rows: orgRows } = await client.query<{ id: string }>(
      `insert into public.organizations (name) values ('Task6 Org') returning id`,
    );
    const orgId = orgRows[0].id;
    const { rows: userRows } = await client.query<{ id: string }>(
      `insert into auth.users default values returning id`,
    );
    const userId = userRows[0].id;
    await client.query(
      `insert into public.profiles (user_id, display_name) values ($1, $2)`,
      [userId, `T6 ${role}`],
    );
    await client.query(
      `insert into public.memberships (organization_id, user_id, role, status)
       values ($1, $2, $3, 'active')`,
      [orgId, userId, role],
    );
    return { orgId, userId };
  }

  it('active organization_admin can update another membership in same tenant', async () => {
    const { orgId, userId: adminId } = await createOrgWithAdmin('organization_admin');
    const { userId: targetUserId } = await createOrgWithAdmin('user');
    // Add targetUserId to the admin's org as a plain user.
    await client.query(
      `insert into public.memberships (organization_id, user_id, role, status)
       values ($1, $2, 'user', 'active')`,
      [orgId, targetUserId],
    );
    await asAuthenticated(client, adminId, async () => {
      const { rowCount } = await client.query(
        `update public.memberships set role = 'manager'
          where organization_id = $1 and user_id = $2`,
        [orgId, targetUserId],
      );
      expect(rowCount).toBe(1);
      // Verify the change is visible within the same transaction.
      const { rows } = await client.query<{ role: string }>(
        `select role from public.memberships
          where organization_id = $1 and user_id = $2`,
        [orgId, targetUserId],
      );
      expect(rows[0].role).toBe('manager');
    });
  });

  it('user role UPDATE in own tenant is silently filtered by RLS (rowCount=0)', async () => {
    const { orgId, userId } = await createOrgWithAdmin('user');
    const { userId: targetId } = await createOrgWithAdmin('user');
    await client.query(
      `insert into public.memberships (organization_id, user_id, role, status)
       values ($1, $2, 'user', 'active')`,
      [orgId, targetId],
    );
    await asAuthenticated(client, userId, async () => {
      // memberships_update_admin USING requires 'organization_admin'; a 'user'
      // caller fails the predicate, so the WHERE clause matches 0 rows.
      // UPDATE returns success but no rows change. RLS does NOT throw — it
      // filters. The Nest layer is the first defense (it 403s on role).
      const { rowCount } = await client.query(
        `update public.memberships set role = 'manager'
          where organization_id = $1 and user_id = $2`,
        [orgId, targetId],
      );
      expect(rowCount).toBe(0);
    });
    const { rows } = await client.query<{ role: string }>(
      `select role from public.memberships
        where organization_id = $1 and user_id = $2`,
      [orgId, targetId],
    );
    expect(rows[0].role).toBe('user');
  });

  it('suspended caller UPDATE is silently filtered by RLS (rowCount=0)', async () => {
    const { orgId, userId: adminId } = await createOrgWithAdmin('organization_admin');
    const { userId: suspendedId } = await createOrgWithAdmin('user');
    // Move suspendedId into the admin's org and suspend them there.
    await client.query(
      `delete from public.memberships where user_id = $1`,
      [suspendedId],
    );
    await client.query(
      `insert into public.memberships (organization_id, user_id, role, status)
       values ($1, $2, 'user', 'suspended')`,
      [orgId, suspendedId],
    );
    void adminId;
    await asAuthenticated(client, suspendedId, async () => {
      const { rowCount } = await client.query(
        `update public.memberships set status = 'active'
          where organization_id = $1 and user_id = $2`,
        [orgId, suspendedId],
      );
      expect(rowCount).toBe(0);
    });
  });

  it('cross-tenant UPDATE via RLS-context returns 0 rows (RLS hides foreign tenant before any check)', async () => {
    const { orgId: foreignOrg } = await createOrgWithAdmin('organization_admin');
    const { userId: foreignAdmin } = await createOrgWithAdmin('user');
    await client.query(
      `update public.memberships set organization_id = $1, user_id = $2
       where organization_id = $1 and user_id = $2`,
      [foreignOrg, foreignAdmin],
    );
    void foreignAdmin;
    // Active admin in their own org tries to update a membership in foreign
    // org. RLS hides the foreign row, so UPDATE matches 0 rows; client sees
    // success but row unchanged.
    const { orgId: ownOrg } = await createOrgWithAdmin('organization_admin');
    const { rows: ownAdminRows } = await client.query<{ user_id: string }>(
      `select user_id from public.memberships
        where organization_id = $1 and role = 'organization_admin'`,
      [ownOrg],
    );
    const ownAdminId = ownAdminRows[0].user_id;
    await asAuthenticated(client, ownAdminId, async () => {
      const { rowCount } = await client.query(
        `update public.memberships set role = 'manager'
          where organization_id = $1`,
        [foreignOrg],
      );
      expect(rowCount).toBe(0);
    });
  });

  it('final-admin self-demotion blocked by enforce_last_admin() trigger', async () => {
    const { orgId, userId } = await createOrgWithAdmin('organization_admin');
    await expect(
      client.query(
        `update public.memberships set role = 'manager'
          where organization_id = $1 and user_id = $2`,
        [orgId, userId],
      ),
    ).rejects.toMatchObject({ message: expect.stringMatching(/last_admin/) });
  });

  it('final-admin self-suspension blocked by enforce_last_admin() trigger', async () => {
    const { orgId, userId } = await createOrgWithAdmin('organization_admin');
    await expect(
      client.query(
        `update public.memberships set status = 'suspended'
          where organization_id = $1 and user_id = $2`,
        [orgId, userId],
      ),
    ).rejects.toMatchObject({ message: expect.stringMatching(/last_admin/) });
  });

  it('two-admin race: exactly one demotion succeeds, the other raises last_admin', async () => {
    const { orgId } = await createOrgWithAdmin('organization_admin');
    const { userId: secondAdmin } = await createOrgWithAdmin('organization_admin');
    await client.query(
      `insert into public.memberships (organization_id, user_id, role, status)
       values ($1, $2, 'organization_admin', 'active')`,
      [orgId, secondAdmin],
    );
    const { rows: aRows } = await client.query<{ user_id: string }>(
      `select user_id from public.memberships
        where organization_id = $1 and role = 'organization_admin' and status = 'active'
        order by user_id asc limit 1`,
      [orgId],
    );
    const firstAdmin = aRows[0].user_id;
    const otherAdmin =
      firstAdmin === secondAdmin
        ? (await client.query<{ user_id: string }>(
            `select user_id from public.memberships
              where organization_id = $1 and role = 'organization_admin' and status = 'active'
              order by user_id desc limit 1`,
            [orgId],
          )).rows[0].user_id
        : secondAdmin;

    // Run both demotions in two separate pg clients in parallel; one must
    // succeed, the other must fail with last_admin (P0001).
    const c1 = new Client({ connectionString });
    const c2 = new Client({ connectionString });
    await Promise.all([c1.connect(), c2.connect()]);
    try {
      const tx1 = c1
        .query('begin')
        .then(() => c1.query(`update public.memberships set role = 'manager' where user_id = $1`, [firstAdmin]))
        .then(() => c1.query('commit'))
        .then(() => 'ok' as const)
        .catch((err: unknown) => {
          void c1.query('rollback').catch(() => {});
          return err instanceof Error && /last_admin/.test(err.message)
            ? ('last_admin' as const)
            : Promise.reject(err);
        });
      const tx2 = c2
        .query('begin')
        .then(() => c2.query(`update public.memberships set role = 'manager' where user_id = $1`, [otherAdmin]))
        .then(() => c2.query('commit'))
        .then(() => 'ok' as const)
        .catch((err: unknown) => {
          void c2.query('rollback').catch(() => {});
          return err instanceof Error && /last_admin/.test(err.message)
            ? ('last_admin' as const)
            : Promise.reject(err);
        });
      const outcomes = await Promise.all([tx1, tx2]);
      // Exactly one ok and one last_admin.
      expect(outcomes.filter((o) => o === 'ok')).toHaveLength(1);
      expect(outcomes.filter((o) => o === 'last_admin')).toHaveLength(1);
    } finally {
      await c1.end().catch(() => {});
      await c2.end().catch(() => {});
    }
  });
});

// ----------------------------------------------------------------------------
// Task 7 — invoice ownership + state transitions + allowlists.
// Uses the deterministic seed (alphaUserA owns an Alpha draft,
// alphaUserB owns an Alpha issued; betaAdmin owns a Beta issued). All
// queries run under SET LOCAL role authenticated with the caller's JWT
// claims, exactly as the caller-scoped Supabase client does in prod.
// ----------------------------------------------------------------------------

describe('Task 7: invoice ownership + state (RLS)', () => {
  let client: Client;

  beforeAll(async () => {
    client = new Client({ connectionString });
    await client.connect();
  });
  afterAll(async () => { await client.end(); });

  it('active user A sees own Alpha invoice and Alpha issued invoice as owner', async () => {
    const token = await signIn(SEED_IDENTITIES.alphaUserA);
    const claims = await decodeAccessToken(token);
    await asAuthenticated(client, claims.sub, async () => {
      const { rows } = await client.query<{ id: string }>(
        `select id from public.invoices where organization_id = $1 order by id asc`,
        [SEED_IDS.alphaOrg],
      );
      // alphaUserA owns the Alpha draft; the Alpha issued invoice is
      // hidden by RLS (owner_id ≠ auth.uid() and role is `user`).
      expect(rows.map((r) => r.id)).toEqual([SEED_IDS.alphaUserAInvoiceDraft]);
    });
  });

  it('active manager sees all Alpha invoices (org-wide visibility)', async () => {
    const token = await signIn(SEED_IDENTITIES.alphaManager);
    const claims = await decodeAccessToken(token);
    await asAuthenticated(client, claims.sub, async () => {
      const { rows } = await client.query<{ id: string }>(
        `select id from public.invoices where organization_id = $1 order by id asc`,
        [SEED_IDS.alphaOrg],
      );
      const ids = rows.map((r) => r.id).sort();
      expect(ids).toEqual(
        [SEED_IDS.alphaUserAInvoiceDraft, SEED_IDS.alphaUserBInvoiceIssued].sort(),
      );
    });
  });

  it('active admin sees all Alpha invoices (org-wide visibility)', async () => {
    const token = await signIn(SEED_IDENTITIES.alphaAdmin);
    const claims = await decodeAccessToken(token);
    await asAuthenticated(client, claims.sub, async () => {
      const { rows } = await client.query<{ id: string }>(
        `select id from public.invoices where organization_id = $1 order by id asc`,
        [SEED_IDS.alphaOrg],
      );
      const ids = rows.map((r) => r.id).sort();
      expect(ids).toEqual(
        [SEED_IDS.alphaUserAInvoiceDraft, SEED_IDS.alphaUserBInvoiceIssued].sort(),
      );
    });
  });

  it('cross-tenant: alpha user SELECTing Beta invoice is hidden (0 rows)', async () => {
    const token = await signIn(SEED_IDENTITIES.alphaUserA);
    const claims = await decodeAccessToken(token);
    await asAuthenticated(client, claims.sub, async () => {
      const { rows } = await client.query<{ id: string }>(
        `select id from public.invoices where id = $1`,
        [SEED_IDS.betaAdminInvoice],
      );
      expect(rows).toEqual([]);
    });
  });

  it('user A INSERTing an invoice sets owner_id from auth.uid() (DB-derived default)', async () => {
    // Reset the user's own session and INSERT one — owner_id is not in the
    // INSERT column grant; it must be defaulted via auth.uid(). This proves
    // the API doesn't need to send owner_id and direct PostgREST cannot
    // override it.
    const token = await signIn(SEED_IDENTITIES.alphaUserA);
    const claims = await decodeAccessToken(token);
    await expect(
      asAuthenticated(client, claims.sub, async () => {
        // The user role is `user`; invoices_insert_manager requires
        // manager|organization_admin. RLS rejects the INSERT.
        await client.query(
          `insert into public.invoices
             (organization_id, customer_id, description, amount_minor, currency)
           values ($1, 'cust', 'desc', 100, 'USD')`,
          [SEED_IDS.alphaOrg],
        );
      }),
    ).rejects.toMatchObject({ code: '42501' });
  });

  it('manager INSERTing an invoice succeeds; owner_id is auth.uid()', async () => {
    const token = await signIn(SEED_IDENTITIES.alphaManager);
    const claims = await decodeAccessToken(token);
    await asAuthenticated(client, claims.sub, async () => {
      const { rows } = await client.query<{ owner_id: string }>(
        `insert into public.invoices
           (organization_id, customer_id, description, amount_minor, currency)
         values ($1, 'cust-x', 'desc-x', 500, 'USD')
         returning owner_id`,
        [SEED_IDS.alphaOrg],
      );
      expect(rows[0].owner_id).toBe(SEED_IDS.alphaManager);
    });
  });

  it('UPDATE setting status to paid for an already-paid invoice is a no-op (self-transition allowed)', async () => {
    // asSuperuserTx rolls back at the end so we can't observe the change
    // across queries. Instead, drive the UPDATE inside an explicit
    // transaction and query within the same transaction before commit.
    await client.query('begin');
    try {
      // First move issued → paid.
      await client.query(
        `update public.invoices set status = 'paid' where id = $1`,
        [SEED_IDS.alphaUserBInvoiceIssued],
      );
      // Now self-transition paid → paid: trigger is no-op.
      await client.query(
        `update public.invoices set status = 'paid' where id = $1`,
        [SEED_IDS.alphaUserBInvoiceIssued],
      );
      const { rows } = await client.query<{ status: string }>(
        `select status from public.invoices where id = $1`,
        [SEED_IDS.alphaUserBInvoiceIssued],
      );
      expect(rows[0].status).toBe('paid');
    } finally {
      await client.query('rollback');
    }
  });

  it('paid → cancelled is rejected by trigger (invalid_state, P0001)', async () => {
    // Drive the UPDATE inside a transaction so the trigger fires; rollback
    // regardless of outcome.
    await client.query('begin');
    let thrown: unknown;
    try {
      await client.query(
        `update public.invoices set status = 'paid' where id = $1`,
        [SEED_IDS.alphaUserBInvoiceIssued],
      );
      try {
        await client.query(
          `update public.invoices set status = 'cancelled' where id = $1`,
          [SEED_IDS.alphaUserBInvoiceIssued],
        );
      } catch (err) {
        thrown = err;
      }
    } finally {
      await client.query('rollback');
    }
    expect(thrown).toMatchObject({ message: expect.stringMatching(/invalid_state/) });
  });

  it('issued → draft is rejected by trigger (invalid_state, P0001)', async () => {
    await client.query('begin');
    let thrown: unknown;
    try {
      // alphaUserAInvoiceDraft starts at 'draft'; first move to 'issued',
      // then try issued → draft. Both within one transaction so the
      // intermediate state is visible to the trigger.
      await client.query(
        `update public.invoices set status = 'issued' where id = $1`,
        [SEED_IDS.alphaUserAInvoiceDraft],
      );
      try {
        await client.query(
          `update public.invoices set status = 'draft' where id = $1`,
          [SEED_IDS.alphaUserAInvoiceDraft],
        );
      } catch (err) {
        thrown = err;
      }
    } finally {
      await client.query('rollback');
    }
    expect(thrown).toMatchObject({ message: expect.stringMatching(/invalid_state/) });
  });

  it('CHECK constraint: amount_minor = 9007199254740991 is accepted', async () => {
    await asSuperuserTx(client, async () => {
      // 9007199254740991 is exactly Number.MAX_SAFE_INTEGER in JS.
      const { rows } = await client.query<{ amount_minor: string }>(
        `update public.invoices set amount_minor = 9007199254740991 where id = $1 returning amount_minor`,
        [SEED_IDS.alphaUserAInvoiceDraft],
      );
      expect(rows[0].amount_minor).toBe('9007199254740991');
    });
  });

  it('CHECK constraint: amount_minor = 9007199254740992 is rejected (23514)', async () => {
    await expect(
      client.query(
        `update public.invoices set amount_minor = 9007199254740992 where id = $1`,
        [SEED_IDS.alphaUserAInvoiceDraft],
      ),
    ).rejects.toMatchObject({ code: '23514' });
  });

  it('CHECK constraint: currency = USDD is rejected (22001 char(3) truncation)', async () => {
    await expect(
      client.query(
        `update public.invoices set currency = 'USDD' where id = $1`,
        [SEED_IDS.alphaUserAInvoiceDraft],
      ),
    ).rejects.toMatchObject({ code: '22001' });
  });
});

// ----------------------------------------------------------------------------
// Task 7 — invoice visibility, ownership, and RLS-denied writes.
// Exercises the existing invoices_select_visible, invoices_insert_manager,
// invoices_update_manager policies. The Postgres trigger
// enforce_invoice_state_transition() is also covered at the SQL boundary.
// ----------------------------------------------------------------------------

describe('Task 7: invoice visibility', () => {
  let client: Client;
  let orgId: string;
  let userAId: string;
  let userBId: string;
  let managerId: string;
  let invoiceOwnedByA: string;
  let invoiceOwnedByB: string;

  beforeAll(async () => {
    client = new Client({ connectionString });
    await client.connect();
    const { rows: orgRows } = await client.query<{ id: string }>(
      `insert into public.organizations (name) values ('Task7 Org') returning id`,
    );
    orgId = orgRows[0].id;

    async function mkUser(role: 'user' | 'manager'): Promise<string> {
      const { rows } = await client.query<{ id: string }>(
        `insert into auth.users default values returning id`,
      );
      const id = rows[0].id;
      await client.query(
        `insert into public.profiles (user_id, display_name) values ($1, $2)`,
        [id, `T7 ${role}`],
      );
      await client.query(
        `insert into public.memberships (organization_id, user_id, role, status)
         values ($1, $2, $3, 'active')`,
        [orgId, id, role],
      );
      return id;
    }

    userAId = await mkUser('user');
    userBId = await mkUser('user');
    managerId = await mkUser('manager');

    async function mkInvoice(ownerId: string): Promise<string> {
      const { rows } = await client.query<{ id: string }>(
        `insert into public.invoices
           (organization_id, owner_id, customer_id, description, amount_minor, currency, status)
         values ($1, $2, 'cust', 'desc', 1000, 'USD', 'draft')
         returning id`,
        [orgId, ownerId],
      );
      return rows[0].id;
    }

    invoiceOwnedByA = await mkInvoice(userAId);
    invoiceOwnedByB = await mkInvoice(userBId);
  });
  afterAll(async () => { await client.end(); });

  it('active user sees ONLY own invoice (invoices_select_visible: user branch)', async () => {
    await asAuthenticated(client, userAId, async () => {
      const { rows } = await client.query<{ id: string }>(
        `select id from public.invoices where organization_id = $1 order by id asc`,
        [orgId],
      );
      expect(rows.map((r) => r.id)).toEqual([invoiceOwnedByA]);
    });
  });

  it("active user sees 0 rows for another user's invoice", async () => {
    await asAuthenticated(client, userAId, async () => {
      const { rows } = await client.query<{ id: string }>(
        `select id from public.invoices where id = $1`,
        [invoiceOwnedByB],
      );
      expect(rows).toEqual([]);
    });
  });

  it('manager sees all invoices in the organization (invoices_select_visible: manager branch)', async () => {
    await asAuthenticated(client, managerId, async () => {
      const { rows } = await client.query<{ id: string }>(
        `select id from public.invoices where organization_id = $1 order by id asc`,
        [orgId],
      );
      expect(rows.map((r) => r.id).sort()).toEqual(
        [invoiceOwnedByA, invoiceOwnedByB].sort(),
      );
    });
  });

  it("user UPDATE on another user's invoice matches 0 rows (RLS filters via USING)", async () => {
    await asAuthenticated(client, userAId, async () => {
      const { rowCount } = await client.query(
        `update public.invoices set status = 'issued' where id = $1`,
        [invoiceOwnedByB],
      );
      expect(rowCount).toBe(0);
    });
  });
});

describe('Task 7: invoice insert RLS', () => {
  let client: Client;
  let orgId: string;
  let userId: string;
  let managerId: string;

  beforeAll(async () => {
    client = new Client({ connectionString });
    await client.connect();
    const { rows: orgRows } = await client.query<{ id: string }>(
      `insert into public.organizations (name) values ('Task7 Insert') returning id`,
    );
    orgId = orgRows[0].id;
    async function mkUser(role: 'user' | 'manager'): Promise<string> {
      const { rows } = await client.query<{ id: string }>(
        `insert into auth.users default values returning id`,
      );
      const id = rows[0].id;
      await client.query(
        `insert into public.profiles (user_id, display_name) values ($1, $2)`,
        [id, `T7i ${role}`],
      );
      await client.query(
        `insert into public.memberships (organization_id, user_id, role, status)
         values ($1, $2, $3, 'active')`,
        [orgId, id, role],
      );
      return id;
    }
    userId = await mkUser('user');
    managerId = await mkUser('manager');
  });
  afterAll(async () => { await client.end(); });

  it('user INSERT is rejected by RLS WITH CHECK (policy violation)', async () => {
    // Unlike SELECT/UPDATE (which silently filter via USING), INSERT with a
    // failing WITH CHECK throws "new row violates row-level security policy".
    // The error code is 42501 (insufficient_privilege). Nest maps this to
    // 403 forbidden or 404 not_found depending on the service layer.
    await expect(
      asAuthenticated(client, userId, async () => {
        await client.query(
          `insert into public.invoices
             (organization_id, customer_id, description, amount_minor, currency)
           values ($1, 'cust', 'desc', 100, 'USD')`,
          [orgId],
        );
      }),
    ).rejects.toMatchObject({ code: '42501' });
  });

  it('manager INSERT succeeds and DB defaults owner_id = auth.uid(), status = draft', async () => {
    await asAuthenticated(client, managerId, async () => {
      const { rows } = await client.query<{ owner_id: string; status: string }>(
        `insert into public.invoices
           (organization_id, customer_id, description, amount_minor, currency)
         values ($1, 'cust', 'desc', 100, 'USD')
         returning owner_id, status`,
        [orgId],
      );
      expect(rows[0].owner_id).toBe(managerId);
      expect(rows[0].status).toBe('draft');
    });
  });

  it('insert with privileged fields (owner_id, organization_id) is rejected by column grant', async () => {
    // Spec §6.2: owner_id column is not granted to `authenticated`. INSERT
    // attempting to set owner_id is rejected with 42501.
    await expect(
      asAuthenticated(client, managerId, async () => {
        await client.query(
          `insert into public.invoices
             (organization_id, owner_id, customer_id, description, amount_minor, currency)
           values ($1, $2, 'cust', 'desc', 100, 'USD')`,
          [orgId, managerId],
        );
      }),
    ).rejects.toMatchObject({ code: '42501' });
  });
});
